In [1]:
import sys
sys.path.append("..")

from src.supertrend import load_raw_data
from src.monthly_range import compute_monthly_range, save_monthly_range

df = load_raw_data("BHARTIARTL")
monthly = compute_monthly_range(df)

monthly.head(10)

/Users/hgmac/Library/CloudStorage/OneDrive-Personal/1 Files/2_harsh/1_harsh_work/3_trading/Quant/notebooks/../src/monthly_range.py:15: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["year_month"] = df.index.to_period("M")

,year_month,month_open,month_high,month_low,month_close,candles,range_pct,net_move_pct
0,2022-01,687.80,752.10,677.50,729.55,40,10.85,6.07
1,2022-02,733.00,735.00,645.90,684.00,40,12.16,-6.68
2,2022-03,684.00,769.90,639.30,757.00,42,19.09,10.67
3,2022-04,759.80,780.55,717.60,740.00,38,8.29,-2.61
4,2022-05,734.00,742.80,667.95,705.15,42,10.20,-3.93
5,2022-06,701.55,705.85,634.25,684.90,44,10.21,-2.37
6,2022-07,684.85,696.60,628.75,677.95,42,9.91,-1.01
7,2022-08,677.95,753.90,677.50,725.20,40,11.27,6.97
8,2022-09,726.50,809.00,686.20,799.60,44,16.90,10.06
9,2022-10,803.40,833.80,759.85,832.00,37,9.20,3.56

In [2]:
save_monthly_range(monthly, "BHARTIARTL")

Saved 55 months to /Users/hgmac/Library/CloudStorage/OneDrive-Personal/1 Files/2_harsh/1_harsh_work/3_trading/Quant/exports/BHARTIARTL_monthly_range.csv

'/Users/hgmac/Library/CloudStorage/OneDrive-Personal/1 Files/2_harsh/1_harsh_work/3_trading/Quant/exports/BHARTIARTL_monthly_range.csv'

In [4]:
monthly.head(10)

,year_month,month_open,month_high,month_low,month_close,candles,range_pct,net_move_pct
0,2022-01,687.80,752.10,677.50,729.55,40,10.85,6.07
1,2022-02,733.00,735.00,645.90,684.00,40,12.16,-6.68
2,2022-03,684.00,769.90,639.30,757.00,42,19.09,10.67
3,2022-04,759.80,780.55,717.60,740.00,38,8.29,-2.61
4,2022-05,734.00,742.80,667.95,705.15,42,10.20,-3.93
5,2022-06,701.55,705.85,634.25,684.90,44,10.21,-2.37
6,2022-07,684.85,696.60,628.75,677.95,42,9.91,-1.01
7,2022-08,677.95,753.90,677.50,725.20,40,11.27,6.97
8,2022-09,726.50,809.00,686.20,799.60,44,16.90,10.06
9,2022-10,803.40,833.80,759.85,832.00,37,9.20,3.56

In [5]:
monthly["range_pct"].describe()

count    55.000000
mean     10.060545
std       3.704218
min       5.470000
25%       7.470000
50%       9.200000
75%      11.770000
max      22.410000
Name: range_pct, dtype: float64