# Stage 10 (repurposed) — General F&O trend-following 1D status (live refresh, full universe)

**REPURPOSED** (see `trend_universe.py` and README Stage 10 for the
history): the universe is now the full F&O stock+index universe, not the
154-symbol pledgeable-securities list. The strategy is unchanged in spirit —
buy on a fresh 1D Supertrend UP flip, hold, exit on the opposite DOWN flip —
but it's now literal cash-equity ownership for any of these names, not
specifically about monitoring pledged collateral. **No stop-loss**:
`src/stop_loss_test.py` backtested fixed-%, ATR-multiple, and worst-day-based
candidate stop rules against real 1D flip history and found none beat holding
to the natural DOWN-flip exit — every rule's stopped-out flips would have
averaged a POSITIVE outcome if held (consistent with `reversion_test.py`'s
momentum/continuation finding). Exit is the Supertrend DOWN flip only, by
design, not by omission — `buffer_to_flip_pct`/`moved_since_entry_pct` below
remain the informational "how close/how underwater" numbers.

**Corrected design (kept from the original build):** a purely read-only
version can go stale the same way the credit-spread screener's already-
documented gap works - if a symbol flipped after the last fetch, the saved
report keeps showing the old direction/age. This version genuinely refreshes
every symbol before reporting status.

**Second correction - a real regression found while building the Stage 11
pledged-trend-following ranking:** the original version of this cell called
`run_all_instruments(..., force_refresh=True)` with a short 390-day window,
which does a full REPLACE of each symbol's saved raw data, not an update.
Every routine live-screener run was silently throwing away notebook 10's deep
multi-year history and replacing it with just that short window - after
repeated runs, every symbol's saved history had collapsed to ~1 year, and
UP-closed-flip counts per symbol fell to 1-8, nowhere near usable for a
ranking. Fixed by switching to `incremental=True`
(`process_instrument_incremental()` in `trend_1d_pipeline.py`): it EXTENDS
existing saved history with just the recent catch-up window instead of
replacing it outright, so routine checks no longer erode the deep history
notebook 10 built. `from_date` is no longer meaningful in this mode (each
symbol's own last-saved date drives its fetch window) - only `to_date` and
`delay_seconds` still apply.

**Rate limit hit three times in a row** even after the chunk-pacing fix in
`fetch_data.py` and a 1-second between-symbol delay - close-to-the-limit
pacing (~0.35-0.4s spacing, right at the documented 3 req/sec ceiling) isn't
leaving enough real-world margin for network jitter, and repeated failures in
the same session may also mean Kite briefly throttles further after tripping
the limit once. `delay_seconds=1.0` between symbols - real headroom, not the
minimum. If this still fails, it's worth waiting a minute or two before
retrying, in case of a lingering cooldown from the earlier attempts.

## Column reference

**Is the trend intact?**

| Column | Meaning |
|---|---|
| `direction` | The currently OPEN 1D Supertrend flip |
| `trend_age_days` | Calendar days since that flip |
| `spot` · `flip_level` | Latest close, and the Supertrend level that would reverse the trend |
| `buffer_to_flip_pct` | Distance between them. **Small = about to invalidate.** With no stop-loss (see below), this is the single most actionable "how close to the exit" number here |
| `moved_since_entry_pct` | Signed *for* the trend: positive = working, negative = underwater |

**Does the signal actually work on this instrument?**

| Column | Meaning |
|---|---|
| `dir_flips` | Closed flips on the currently open side. Under 10, the edge columns are blank |
| `dir_win_rate` | % of those that moved the way the signal called |
| `dir_median_move` | Median favourable move. Negative = the typical flip goes the *wrong* way |
| `signal_works_here` | `dir_win_rate >= 50` **and** `dir_median_move > 0` |
| `opp_win_rate` · `opp_median_move` | The other direction, for contrast only |

> **Why this matters on this universe.** Measured on the original 154-symbol
> pledged universe (100 instruments with enough history): UP flips won 54.1%
> (+0.9% mean median move, 68% show an edge). DOWN flips won **42.4%** with a
> **−1.3%** mean median move and only **14%** show an edge — the median DOWN
> flip ends with price *higher* than where it flipped. Worth re-checking this
> split on the full F&O universe once enough calendar time has passed, but
> UP-only scoring is the right default in the meantime.

**No stop-loss.** `src/stop_loss_test.py` tested fixed-% (5/8/10/12%),
ATR-multiple (1.5×/2×/2.5×), and worst-day-based candidate stop rules against
real closed UP flips — every single one reduced mean/median return and win
rate versus simply holding to the natural DOWN-flip exit, because stopped-out
flips consistently would have recovered to a profit if held (consistent with
`reversion_test.py`'s momentum/continuation finding, not reversion). Exit is
the Supertrend DOWN flip only.

**Risk / event context**

| Column | Meaning |
|---|---|
| `worst_day` | Largest single close-to-close day against the position, 4yr |
| `entry_day_move` | Move on the day this flip was born |
| `born_on_outlier_day` | `abs(entry_day_move) > 4%` — a flip created by a one-day collapse is a different event, and the duration stats come from ordinary flips |

**Duration context** — descriptive only

| Column | Meaning |
|---|---|
| `median_duration` | This instrument's typical 1D flip length |
| `past_median` · `past_75th_pct` · `past_90th_pct` | Has the open trend outlived that checkpoint? |
| `runway_left_vs_median` · `_p75` · `_p90` | `checkpoint − age` in signed days; negative = past it |

> `reversion_test.py` and `exhaustion_test.py` both found that crossing a duration
> checkpoint does **not** predict a reversal. Not a warning, not an exit signal.

**Universe & score** *(from `trend_universe.py` and notebook 12)*

| Column | Meaning |
|---|---|
| `security_type` | `Stock` or `Index` — display/filter only, not a separate scoring scale |
| `trend_score` | UP-trend-following rank from notebook 12. Blank = thin sample, not a low score |
| `thin_sample` | Fewer than 15 UP-closed flips, so unscored |
| `outlier_reliance_flag` · `gap_risk_flag` | Score depends on a few outlier wins / high gap history |

*All statistics are in-sample and descriptive — what the signal HAS done, not what it will do.*

In [1]:
import sys
sys.path.append("..")

from datetime import datetime, timedelta
from src.auth import get_kite
from src.instruments import build_nse_token_lookup, get_index_token_lookup
from src.trend_universe import load_trend_universe, save_trend_universe
from src.trend_1d_pipeline import run_all_instruments

kite = get_kite()
universe = load_trend_universe(kite=kite)
save_trend_universe(fno_symbol_list=universe[universe.security_type == "Stock"]["symbol"].tolist())
symbol_list = universe["symbol"].tolist()

token_lookup = build_nse_token_lookup(kite)
token_lookup.update(get_index_token_lookup(kite))

# incremental=True - EXTENDS each symbol's existing saved history with just
# the recent catch-up window (per-symbol, derived from its own last-saved
# date) instead of replacing it outright. from_date is unused in this mode,
# kept only because run_all_instruments still accepts it positionally.
#
# delay_seconds bumped well past the 3 req/sec limit's minimum spacing
# (~0.33s) - three failed attempts in a row means it's worth real headroom
# over cutting it close, even though it makes the full run slower.
results = run_all_instruments(
    kite, token_lookup, symbol_list,
    from_date=None,
    to_date=datetime.now(),
    incremental=True,
    delay_seconds=1.0
)
results["status"].value_counts()

Saved 217 symbols (211 stocks, 6 indices) to /Users/hgmac/Documents/3_trading/Quant/config/trend_universe.csv
[1/217] 360ONE — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 1981 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/360ONE_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/360ONE_full_report.xlsx
[1/217] 360ONE — done
[2/217] ABB — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ABB_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ABB_full_report.xlsx
[2/217] ABB — done
[3/217] ABCAPITAL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2229 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ABCAPITAL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ABCAPITAL_full_report.xlsx
[3/217] ABCAPITAL — done
[4/217] ADANIENSOL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2743 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ADANIENSOL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ADANIENSOL_full_report.xlsx
[4/217] ADANIENSOL — done
[5/217] ADANIENT — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ADANIENT_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ADANIENT_full_report.xlsx
[5/217] ADANIENT — done
[6/217] ADANIGREEN — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2033 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ADANIGREEN_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ADANIGREEN_full_report.xlsx
[6/217] ADANIGREEN — done
[7/217] ADANIPORTS — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ADANIPORTS_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ADANIPORTS_full_report.xlsx
[7/217] ADANIPORTS — done
[8/217] ADANIPOWER — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ADANIPOWER_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ADANIPOWER_full_report.xlsx
[8/217] ADANIPOWER — done
[9/217] ALKEM — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2646 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ALKEM_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ALKEM_full_report.xlsx
[9/217] ALKEM — done
[10/217] AMBER — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2127 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/AMBER_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/AMBER_full_report.xlsx
[10/217] AMBER — done
[11/217] AMBUJACEM — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/AMBUJACEM_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/AMBUJACEM_full_report.xlsx
[11/217] AMBUJACEM — done
[12/217] ANGELONE — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 1467 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ANGELONE_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ANGELONE_full_report.xlsx
[12/217] ANGELONE — done
[13/217] APLAPOLLO — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/APLAPOLLO_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/APLAPOLLO_full_report.xlsx
[13/217] APLAPOLLO — done
[14/217] APOLLOHOSP — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/APOLLOHOSP_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/APOLLOHOSP_full_report.xlsx
[14/217] APOLLOHOSP — done
[15/217] ASHOKLEY — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ASHOKLEY_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ASHOKLEY_full_report.xlsx
[15/217] ASHOKLEY — done
[16/217] ASIANPAINT — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ASIANPAINT_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ASIANPAINT_full_report.xlsx
[16/217] ASIANPAINT — done
[17/217] ASTRAL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ASTRAL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ASTRAL_full_report.xlsx
[17/217] ASTRAL — done
[18/217] ATHERENERG — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 331 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ATHERENERG_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ATHERENERG_full_report.xlsx
[18/217] ATHERENERG — done
[19/217] AUBANK — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2266 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/AUBANK_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/AUBANK_full_report.xlsx
[19/217] AUBANK — done
[20/217] AUROPHARMA — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/AUROPHARMA_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/AUROPHARMA_full_report.xlsx
[20/217] AUROPHARMA — done
[21/217] AXISBANK — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/AXISBANK_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/AXISBANK_full_report.xlsx
[21/217] AXISBANK — done
[22/217] BAJAJ-AUTO — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BAJAJ-AUTO_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BAJAJ-AUTO_full_report.xlsx
[22/217] BAJAJ-AUTO — done
[23/217] BAJAJFINSV — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BAJAJFINSV_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BAJAJFINSV_full_report.xlsx
[23/217] BAJAJFINSV — done
[24/217] BAJAJHLDNG — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BAJAJHLDNG_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BAJAJHLDNG_full_report.xlsx
[24/217] BAJAJHLDNG — done
[25/217] BAJFINANCE — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BAJFINANCE_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BAJFINANCE_full_report.xlsx
[25/217] BAJFINANCE — done
[26/217] BANDHANBNK — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2089 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BANDHANBNK_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BANDHANBNK_full_report.xlsx
[26/217] BANDHANBNK — done
[27/217] BANKBARODA — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BANKBARODA_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BANKBARODA_full_report.xlsx
[27/217] BANKBARODA — done
[28/217] BANKINDIA — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BANKINDIA_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BANKINDIA_full_report.xlsx
[28/217] BANKINDIA — done
[29/217] BDL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2091 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BDL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BDL_full_report.xlsx
[29/217] BDL — done
[30/217] BEL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BEL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BEL_full_report.xlsx
[30/217] BEL — done
[31/217] BHARATFORG — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BHARATFORG_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BHARATFORG_full_report.xlsx
[31/217] BHARATFORG — done
[32/217] BHARTIARTL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BHARTIARTL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BHARTIARTL_full_report.xlsx
[32/217] BHARTIARTL — done
[33/217] BHEL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BHEL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BHEL_full_report.xlsx
[33/217] BHEL — done
[34/217] BIOCON — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BIOCON_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BIOCON_full_report.xlsx
[34/217] BIOCON — done
[35/217] BLUESTARCO — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BLUESTARCO_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BLUESTARCO_full_report.xlsx
[35/217] BLUESTARCO — done
[36/217] BOSCHLTD — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BOSCHLTD_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BOSCHLTD_full_report.xlsx
[36/217] BOSCHLTD — done
[37/217] BPCL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BPCL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BPCL_full_report.xlsx
[37/217] BPCL — done
[38/217] BRITANNIA — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BRITANNIA_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BRITANNIA_full_report.xlsx
[38/217] BRITANNIA — done
[39/217] BSE — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2371 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/BSE_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/BSE_full_report.xlsx
[39/217] BSE — done
[40/217] CAMS — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 1467 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/CAMS_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/CAMS_full_report.xlsx
[40/217] CAMS — done
[41/217] CANBK — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/CANBK_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/CANBK_full_report.xlsx
[41/217] CANBK — done
[42/217] CDSL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2272 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/CDSL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/CDSL_full_report.xlsx
[42/217] CDSL — done
[43/217] CGPOWER — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/CGPOWER_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/CGPOWER_full_report.xlsx
[43/217] CGPOWER — done
[44/217] CHOLAFIN — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/CHOLAFIN_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/CHOLAFIN_full_report.xlsx
[44/217] CHOLAFIN — done
[45/217] CIPLA — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/CIPLA_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/CIPLA_full_report.xlsx
[45/217] CIPLA — done
[46/217] COALINDIA — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2888 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/COALINDIA_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/COALINDIA_full_report.xlsx
[46/217] COALINDIA — done
[47/217] COCHINSHIP — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2242 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/COCHINSHIP_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/COCHINSHIP_full_report.xlsx
[47/217] COCHINSHIP — done
[48/217] COFORGE — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/COFORGE_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/COFORGE_full_report.xlsx
[48/217] COFORGE — done
[49/217] COLPAL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/COLPAL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/COLPAL_full_report.xlsx
[49/217] COLPAL — done
[50/217] CONCOR — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/CONCOR_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/CONCOR_full_report.xlsx
[50/217] CONCOR — done
[51/217] CROMPTON — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2552 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/CROMPTON_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/CROMPTON_full_report.xlsx
[51/217] CROMPTON — done
[52/217] CUMMINSIND — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/CUMMINSIND_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/CUMMINSIND_full_report.xlsx
[52/217] CUMMINSIND — done
[53/217] DABUR — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/DABUR_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/DABUR_full_report.xlsx
[53/217] DABUR — done
[54/217] DELHIVERY — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 1070 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/DELHIVERY_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/DELHIVERY_full_report.xlsx
[54/217] DELHIVERY — done
[55/217] DIVISLAB — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/DIVISLAB_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/DIVISLAB_full_report.xlsx
[55/217] DIVISLAB — done
[56/217] DIXON — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2218 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/DIXON_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/DIXON_full_report.xlsx
[56/217] DIXON — done
[57/217] DLF — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/DLF_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/DLF_full_report.xlsx
[57/217] DLF — done
[58/217] DMART — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2341 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/DMART_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/DMART_full_report.xlsx
[58/217] DMART — done
[59/217] DRREDDY — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/DRREDDY_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/DRREDDY_full_report.xlsx
[59/217] DRREDDY — done
[60/217] EICHERMOT — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2887 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/EICHERMOT_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/EICHERMOT_full_report.xlsx
[60/217] EICHERMOT — done
[61/217] ETERNAL — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 1268 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/ETERNAL_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/ETERNAL_full_report.xlsx
[61/217] ETERNAL — done
[62/217] FEDERALBNK — processing...
Fetching 2025-07-28 to 2026-08-27...
Fetching 2026-08-28 to 2026-09-01...
Saved 2891 candles to /Users/hgmac/Documents/3_trading/Quant/data/raw/FEDERALBNK_day.csv
Saved full report to /Users/hgmac/Documents/3_trading/Quant/exports/trend_1d/FEDERALBNK_full_report.xlsx
[62/217] FEDERALBNK — done

status
SUCCESS    216
FAILED       1
Name: count, dtype: int64

In [2]:
import pandas as pd

# Every table below is wide (30 columns after the trend_score merge)
# and the Shares table alone is 100+ rows — comfortably past pandas' defaults
# (60 rows, and columns wrap rather than showing all 30 side by side), so both
# axes were truncating with "..." in the middle. Nothing was ever missing from
# the underlying data, just not printed. max_columns=None shows every column;
# width=250 stops them wrapping; max_rows=250 covers the largest table here.
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 250)
pd.set_option("display.max_rows", 250)

In [3]:
from src.trend_1d_screener import check_trend_status
import pandas as pd

results = [check_trend_status(s, universe_df=universe) for s in symbol_list]
results = [r for r in results if r is not None]
status = pd.DataFrame(results).sort_values("trend_age_days")
print("SORTED BY: trend_age_days ascending — sets the order the status_up/top25 tables inherit")
print(f"{len(status)} of {len(symbol_list)} instruments have a current status")

No report found for NIFTYFPI - refresh it first
SORTED BY: trend_age_days ascending — sets the order the status_up/top25 tables inherit
216 of 217 instruments have a current status

In [4]:
# Merge in score_for_trend_following()'s ranking (Stage 10/11) -
# answers "which of several same-day UP flips should I prioritize" instead
# of leaving it a guess. Run notebook 12 first if these files don't exist
# yet or look stale.
ranking = pd.read_excel("../exports/RANKING_trend_following.xlsx")
watchlist = pd.read_excel("../exports/WATCHLIST_trend_following.xlsx")

score_cols = ["symbol", "trend_score", "outlier_reliance_flag", "gap_risk_flag"]
ranking_slim = ranking[score_cols]

# Watchlist symbols have no score yet (below the 15 UP-closed-flip floor) -
# kept as NaN/blank rather than 0, so "no score" is never confused with
# "scored low". thin_sample flags which case applies.
watchlist_slim = watchlist[["symbol"]].copy()
for col in ["trend_score", "outlier_reliance_flag", "gap_risk_flag"]:
    watchlist_slim[col] = None
watchlist_slim["thin_sample"] = True

score_lookup = pd.concat([
    ranking_slim.assign(thin_sample=False),
    watchlist_slim
], ignore_index=True)

status = status.merge(score_lookup, on="symbol", how="left")
print(f"Scored: {status['trend_score'].notna().sum()} of {len(status)} — rest are thin-sample (< 15 UP-closed flips)")

KeyError: "['trend_score'] not in index"

## All instruments — current status

In [ ]:
print("SORTED BY: trend_age_days ascending — most recently flipped first")
status

SORTED BY: trend_age_days ascending — most recently flipped first

,symbol,direction,trend_age_days,median_duration,past_median,past_75th_pct,past_90th_pct,runway_left_vs_median,runway_left_vs_p75,runway_left_vs_p90,dir_flips,dir_win_rate,dir_median_move,worst_day,opp_win_rate,opp_median_move,signal_works_here,spot,flip_level,buffer_to_flip_pct,moved_since_entry_pct,entry_day_move,born_on_outlier_day,security_type,trend_score,outlier_reliance_flag,gap_risk_flag,thin_sample
0,KAYNES,DOWN,0,53.0,False,False,False,53.0,78.0,113.0,10,50.0,-2.42,13.76,81.8,10.86,False,3635.20,4093.08,12.60,-0.00,-1.35,False,Stock,None,None,None,True
1,MARUTI,DOWN,0,39.0,False,False,False,39.0,66.5,115.4,39,43.6,-2.19,13.51,65.0,2.32,False,12926.00,13987.91,8.22,-0.00,-4.58,True,Stock,78.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.22pp),NaN,False
2,M&M,DOWN,0,41.0,False,False,False,41.0,61.0,98.8,39,43.6,-1.45,14.36,52.5,0.28,False,3264.20,3516.32,7.72,-0.00,-0.54,False,Stock,47.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.73pp),NaN,False
3,MUTHOOTFIN,DOWN,0,49.0,False,False,False,49.0,79.5,125.2,33,45.5,-0.37,16.73,55.9,3.16,False,2930.50,3241.34,10.61,-0.00,-1.60,False,Stock,60.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.33pp),NaN,False
4,NIFTYNXT50,DOWN,0,32.0,False,False,False,32.0,51.0,74.8,51,37.3,-1.59,6.39,61.5,0.92,False,73055.90,75065.96,2.75,-0.00,-0.95,False,Index,73.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.16pp),NaN,False
5,ADANIENT,DOWN,1,46.0,False,False,False,45.0,63.5,107.6,37,48.6,-0.60,20.04,50.0,0.60,False,2864.10,3160.04,10.33,-0.17,-9.76,True,Stock,26.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 33.74pp),⚠ HIGH GAP RISK (>10.0%),False
6,BAJFINANCE,DOWN,1,42.0,False,False,False,41.0,70.0,100.0,38,36.8,-2.49,11.06,69.2,7.79,False,1057.30,1122.95,6.21,-0.03,-2.12,False,Stock,91.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.33pp),NaN,False
7,OFSS,UP,1,46.0,False,False,False,45.0,78.2,126.9,34,41.2,-2.24,8.31,41.2,-1.16,False,12220.00,11257.20,7.88,-2.55,2.87,False,Stock,14.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 9.77pp),NaN,False
8,BRITANNIA,DOWN,1,50.0,False,False,False,49.0,86.0,107.2,34,41.2,-1.08,10.61,57.1,2.41,False,5169.50,5511.20,6.61,1.53,-1.10,False,Stock,73.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.05pp),NaN,False
9,AXISBANK,UP,1,54.0,False,False,False,53.0,87.0,112.7,34,67.6,3.66,7.57,38.2,-1.36,True,1266.30,1209.49,4.49,-2.59,2.77,False,Stock,87.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.40pp),NaN,False
10,SUNPHARMA,UP,1,45.5,False,False,False,44.5,70.8,122.2,37,51.4,0.27,6.39,48.6,-0.18,True,1931.30,1839.93,4.73,-2.70,3.37,False,Stock,47.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.78pp),NaN,False
11,CGPOWER,UP,1,45.5,False,False,False,44.5,67.2,97.7,40,57.5,2.99,8.63,40.0,-2.53,True,885.95,827.70,6.57,-3.28,3.04,False,Stock,54.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 14.14pp),NaN,False
12,BHARTIARTL,DOWN,1,46.0,False,False,False,45.0,80.0,129.0,34,38.2,-1.67,10.91,51.4,1.94,False,1871.30,1967.40,5.14,-3.28,-3.75,False,Stock,58.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.20pp),NaN,False
13,BDL,DOWN,1,30.0,False,False,False,29.0,52.0,75.6,36,38.9,-1.84,10.73,35.1,-1.90,False,1257.60,1381.14,9.82,1.36,-2.37,False,Stock,12.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.75pp),⚠ HIGH GAP RISK (>10.0%),False
14,MARICO,DOWN,1,57.0,False,False,False,56.0,90.0,149.2,28,35.7,-2.45,8.69,51.7,3.12,False,837.35,875.01,4.50,-2.12,-1.16,False,Stock,70.0,NaN,NaN,False
15,HEROMOTOCO,DOWN,1,40.0,False,False,False,39.0,72.0,97.6,39,46.2,-0.07,12.63,50.0,0.03,False,5562.50,5883.59,5.77,-2.06,-2.68,False,Stock,40.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.92pp),NaN,False
16,NHPC,DOWN,4,42.0,False,False,False,38.0,73.0,103.0,35,37.1,-1.32,15.18,52.8,0.29,False,75.81,79.64,5.05,-1.32,-2.26,False,Stock,45.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.45pp),NaN,False
17,IEX,DOWN,4,38.0,False,False,False,34.0,75.5,101.8,27,48.1,-1.18,10.25,42.9,-1.20,False,119.30,126.11,5.71,2.05,-0.16,False,Stock,18.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.98pp),NaN,False
18,HAVELLS,DOWN,4,45.0,False,False,False,41.0,67.5,95.0,37,45.9,-2.03,8.40,50.0,0.34,False,1220.70,1303.13,6.75,0.18,-1.46,False,Stock,44.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.70pp),NaN,False
19,ASIANPAINT,DOWN,4,47.0,False,False,False,43.0,67.0,136.0,34,44.1,-1.68,8.85,57.1,2.19,False,2576.00,2750.53,6.78,1.25,-0.85,False,Stock,73.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.04pp),NaN,False
20,TCS,DOWN,5,38.0,False,False,False,33.0,52.0,94.6,42,47.6,-0.54,9.85,53.5,0.24,False,2366.90,2422.57,2.35,-5.27,-0.95,False,Stock,57.6,NaN,NaN,False
21,AMBER,UP,5,50.0,False,False,False,45.0,75.8,96.8,24,45.8,-1.18,10.28,50.0,-0.26,False,7582.50,7160.28,5.57,-1.54,3.15,False,Stock,15.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 15.92pp),⚠ HIGH GAP RISK (>10.0%),False
22,CONCOR,DOWN,5,47.0,False,False,False,42.0,71.0,133.0,34,52.9,0.40,16.09,51.4,0.58,True,517.00,543.69,5.16,-4.86,-4.63,True,Stock,48.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.50pp),NaN,False
23,CDSL,UP,6,36.5,False,False,False,30.5,71.2,128.5,28,39.3,-3.49,9.99,46.4,-0.28,False,1386.90,1329.38,4.15,-3.28,2.81,False,Stock,5.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 15.71pp),NaN,False
24,MAHABANK,UP,6,41.0,False,False,False,35.0,58.2,103.5,38,47.4,-1.69,8.97,42.1,-2.36,False,82.85,78.51,5.24,-3.21,4.77,True,Stock,19.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.12pp),NaN,False
25,CAMS,DOWN,6,33.0,False,False,False,27.0,49.0,96.6,22,36.4,-4.62,9.33,43.5,-3.04,False,755.00,792.63,4.98,-1.21,-0.53,False,Stock,18.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.96pp),NaN,False
26,LICHSGFIN,UP,6,38.0,False,False,False,32.0,65.5,91.0,41,43.9,-0.29,9.49,48.8,-0.42,False,534.40,500.41,6.36,1.91,3.64,False,Stock,33.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.40pp),NaN,False
27,NMDC,UP,6,43.0,False,False,False,37.0,72.2,113.8,36,66.7,3.70,10.08,38.9,-4.27,True,85.96,81.41,5.30,-2.55,2.64,False,Stock,71.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.03pp),NaN,False
28,HDFCAMC,UP,7,33.5,False,False,False,26.5,56.8,102.3,29,48.3,-0.25,6.33,48.3,-0.84,False,2551.30,2517.52,1.32,-5.44,3.06,False,Stock,33.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.67pp),NaN,False
29,TRENT,DOWN,8,43.0,False,False,False,35.0,67.0,95.0,38,31.6,-3.63,12.14,59.0,5.99,False,2887.80,3042.08,5.34,0.59,-0.65,False,Stock,79.8,NaN,NaN,False
30,GLENMARK,UP,8,55.0,False,False,False,47.0,80.5,108.5,33,54.5,2.36,8.35,54.5,0.83,True,2485.80,2299.30,7.50,3.98,3.14,False,Stock,54.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.82pp),NaN,False
31,VMM,UP,8,52.0,False,False,False,44.0,91.2,127.1,4,NaN,NaN,NaN,NaN,NaN,None,108.04,101.93,5.66,-4.81,9.74,True,Stock,None,None,None,True
32,LICI,UP,11,37.0,False,False,False,26.0,86.2,98.3,14,50.0,-0.92,6.57,64.3,2.56,False,414.15,397.40,4.04,-1.92,0.78,False,Stock,None,None,None,True
33,PETRONET,UP,12,52.0,False,False,False,40.0,73.0,88.8,37,45.9,-0.09,5.77,35.1,-2.57,False,292.20,276.47,5.38,0.27,1.13,False,Stock,37.8,NaN,NaN,False
34,JIOFIN,DOWN,13,46.0,False,False,False,33.0,44.0,80.0,10,50.0,-0.75,8.11,27.3,-2.85,False,237.05,252.48,6.51,2.51,-1.08,False,Stock,None,None,None,True
35,ULTRACEMCO,DOWN,13,45.0,False,False,False,32.0,60.0,83.8,38,44.7,-0.69,12.86,56.4,1.16,False,11470.00,12025.06,4.84,-0.17,-0.43,False,Stock,68.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.77pp),NaN,False
36,MANAPPURAM,DOWN,13,54.0,False,False,False,41.0,58.0,91.2,34,32.4,-2.80,20.88,68.6,5.76,False,339.15,372.46,9.82,0.25,-1.90,False,Stock,75.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 9.85pp),⚠ HIGH GAP RISK (>10.0%),False
37,AMBUJACEM,DOWN,13,36.0,False,False,False,23.0,59.5,101.0,39,43.6,-2.70,7.60,40.0,-2.28,False,403.95,430.93,6.68,0.87,-1.19,False,Stock,23.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.92pp),NaN,False
38,ADANIENSOL,DOWN,13,41.0,False,False,False,28.0,65.0,105.0,35,37.1,-3.81,11.99,58.3,9.36,False,1381.10,1595.83,15.55,10.36,-3.89,False,Stock,62.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.56pp),NaN,False
39,SBICARD,DOWN,14,50.0,False,False,False,36.0,52.0,127.0,20,50.0,-0.28,7.53,57.1,1.58,False,636.60,666.69,4.73,-3.51,-4.17,True,Stock,63.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.22pp),NaN,False
40,SBILIFE,DOWN,14,64.0,False,False,False,50.0,71.0,88.0,24,41.7,-3.57,13.10,52.0,0.19,False,1752.70,1833.22,4.59,1.42,-0.69,False,Stock,46.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.02pp),NaN,False
41,TMPV,DOWN,14,43.0,False,False,False,29.0,49.0,79.8,42,52.4,1.16,10.87,55.8,3.66,True,312.10,334.98,7.33,3.31,-2.24,False,Stock,72.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.58pp),NaN,False
42,ITC,DOWN,14,52.0,False,False,False,38.0,69.0,110.4,33,54.5,0.48,8.43,52.9,0.24,True,267.35,275.47,3.04,0.98,-1.12,False,Stock,52.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.35pp),NaN,False
43,MOTILALOFS,UP,15,54.0,False,False,False,39.0,73.0,109.4,32,62.5,3.04,8.08,43.8,-1.02,True,1027.00,953.06,7.20,7.54,5.68,True,Stock,55.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 11.86pp),⚠ HIGH GAP RISK (>10.0%),False
44,OBEROIRLTY,UP,15,49.5,False,False,False,34.5,68.8,138.0,31,64.5,2.78,11.57,32.3,-3.57,True,1879.20,1744.15,7.19,-2.68,4.60,True,Stock,65.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.25pp),NaN,False
45,UPL,DOWN,18,39.0,False,False,False,21.0,52.5,104.0,37,45.9,-0.58,11.74,55.3,0.76,False,566.30,596.67,5.36,-0.59,-0.91,False,Stock,60.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.39pp),NaN,False
46,IDEA,UP,18,40.0,False,False,False,22.0,50.2,98.0,38,36.8,-4.23,16.25,57.9,4.96,False,14.18,13.81,2.64,0.50,4.44,True,Stock,3.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 12.23pp),NaN,False
47,ALKEM,DOWN,18,48.0,False,False,False,30.0,63.0,128.0,30,33.3,-2.68,14.94,45.2,-1.11,False,5298.50,5623.82,6.14,1.29,-1.50,False,Stock,28.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.57pp),NaN,False
48,MANKIND,DOWN,19,38.0,False,False,False,19.0,54.0,70.0,10,20.0,-3.30,9.10,45.5,-2.35,False,2357.50,2494.57,5.81,1.95,-1.18,False,Stock,None,None,None,True
49,BEL,UP,19,38.0,False,False,False,19.0,43.0,83.0,41,53.7,3.72,7.67,34.1,-4.01,True,412.15,394.10,4.38,0.40,1.18,False,Stock,70.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.72pp),NaN,False
50,SHREECEM,DOWN,19,45.0,False,False,False,26.0,56.0,81.0,36,44.4,-0.32,10.07,56.8,0.96,False,23510.00,25319.36,7.70,6.87,-1.27,False,Stock,64.3,NaN,NaN,False
51,FORTIS,DOWN,20,48.0,False,False,False,28.0,67.0,98.0,30,50.0,-0.27,11.82,48.4,-0.14,False,918.40,973.42,5.99,-2.04,-3.76,False,Stock,20.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.54pp),NaN,False
52,FORCEMOT,UP,20,47.5,False,False,False,27.5,51.0,112.9,20,55.0,5.42,9.43,60.0,3.06,True,17874.00,17141.86,4.10,-7.24,5.12,True,Stock,50.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 20.35pp),NaN,False
53,COLPAL,DOWN,20,45.0,False,False,False,25.0,50.0,96.0,34,47.1,-0.71,7.17,51.4,0.34,False,1850.70,1940.71,4.86,7.70,-0.15,False,Stock,49.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.51pp),NaN,False
54,APOLLOHOSP,DOWN,20,37.0,False,False,False,17.0,36.5,79.6,43,27.9,-2.14,15.49,47.7,-1.35,False,8772.50,9132.22,4.10,-2.04,-1.75,False,Stock,28.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.16pp),NaN,False
55,GODREJCP,DOWN,20,52.0,False,False,False,32.0,55.0,78.0,35,48.6,-0.34,7.40,55.6,1.32,False,902.75,958.02,6.12,0.80,-11.22,True,Stock,61.4,NaN,NaN,False
56,PIIND,DOWN,20,58.0,False,False,False,38.0,73.5,148.8,27,51.9,0.81,11.80,53.6,2.66,True,2389.70,2553.84,6.87,3.76,-9.05,True,Stock,52.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.77pp),⚠ HIGH GAP RISK (>10.0%),False
57,CROMPTON,DOWN,21,57.0,False,False,False,36.0,61.0,117.0,26,46.2,-0.52,10.45,48.1,-0.58,False,231.61,253.62,9.50,5.62,-0.87,False,Stock,31.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.62pp),NaN,False
58,POLICYBZR,UP,21,29.5,False,False,False,8.5,31.0,84.0,17,35.3,-5.87,13.34,41.2,-1.33,False,1845.30,1694.96,8.15,6.48,6.32,True,Stock,6.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.30pp),NaN,False
59,BHARATFORG,DOWN,21,37.0,False,False,False,16.0,52.5,91.0,39,35.9,-3.86,19.02,50.0,0.40,False,2056.50,2173.55,5.69,-0.27,-2.01,False,Stock,43.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.16pp),NaN,False
60,MCX,UP,21,39.0,False,False,False,18.0,50.2,99.5,38,42.1,-1.21,14.63,42.1,-1.39,False,3298.50,3054.57,7.40,13.94,4.92,True,Stock,12.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 11.18pp),NaN,False
61,MAXHEALTH,DOWN,21,35.0,False,False,False,14.0,35.5,91.2,17,35.3,-2.53,8.37,61.1,1.38,False,1014.10,1075.48,6.05,2.49,-2.71,False,Stock,47.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 13.71pp),NaN,False
62,RECLTD,DOWN,22,32.0,False,False,False,10.0,53.0,89.0,42,42.9,-1.76,12.44,44.2,-1.34,False,314.65,339.50,7.90,8.47,-6.34,True,Stock,23.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.69pp),NaN,False
63,POWERINDIA,UP,22,36.5,False,False,False,14.5,58.0,109.6,19,63.2,6.81,11.72,36.8,-5.14,True,32760.00,32116.12,1.97,-9.13,10.58,True,Stock,67.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 13.68pp),⚠ HIGH GAP RISK (>10.0%),False
64,VEDL,UP,25,50.0,False,False,False,25.0,52.0,94.5,37,64.9,3.60,14.11,35.1,-2.96,True,276.85,261.17,5.66,-0.72,1.40,False,Stock,65.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 10.76pp),⚠ HIGH GAP RISK (>10.0%),False
65,MAZDOCK,UP,26,33.5,False,False,False,7.5,39.2,64.9,21,57.1,3.70,10.89,38.1,-1.21,True,2486.70,2425.26,2.47,-1.71,6.28,True,Stock,54.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 18.99pp),NaN,False
66,COCHINSHIP,UP,26,49.5,False,False,False,23.5,58.0,83.4,27,44.4,-0.60,11.49,59.3,3.60,False,1482.50,1449.08,2.25,-0.50,4.56,True,Stock,23.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 16.75pp),⚠ HIGH GAP RISK (>10.0%),False
67,VOLTAS,DOWN,26,49.0,False,False,False,23.0,43.0,86.0,35,48.6,-0.21,6.38,55.6,1.70,False,1197.80,1282.01,7.03,6.05,-1.96,False,Stock,62.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.72pp),NaN,False
68,BLUESTARCO,DOWN,26,51.0,False,False,False,25.0,49.0,84.8,31,32.3,-2.31,9.96,56.2,0.41,False,1481.40,1576.01,6.39,5.70,-5.65,True,Stock,42.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 9.44pp),⚠ HIGH GAP RISK (>10.0%),False
69,KOTAKBANK,UP,27,45.0,False,False,False,18.0,61.2,93.0,34,55.9,1.02,6.33,38.2,-1.41,True,425.85,401.57,5.70,6.46,0.50,False,Stock,64.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.61pp),NaN,False
70,NAM-INDIA,UP,27,50.5,False,False,False,23.5,59.2,133.6,20,55.0,0.73,7.74,45.0,-1.96,True,1182.80,1153.85,2.45,-2.65,1.08,False,Stock,34.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 15.51pp),⚠ HIGH GAP RISK (>10.0%),False
71,SAIL,UP,27,41.0,False,False,False,14.0,39.8,69.7,41,51.2,0.25,10.23,46.3,-0.89,True,194.05,176.96,8.81,10.57,1.12,False,Stock,30.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.77pp),NaN,False
72,TATASTEEL,UP,27,43.5,False,False,False,16.5,44.2,80.0,38,65.8,3.76,8.57,42.1,-1.62,True,185.04,180.25,2.59,-4.12,1.07,False,Stock,79.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.92pp),NaN,False
73,HINDALCO,UP,28,43.0,False,False,False,15.0,46.2,87.9,37,64.9,4.37,10.98,35.1,-2.35,True,1021.30,997.57,2.32,0.13,2.52,False,Stock,79.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.15pp),NaN,False
74,HINDZINC,UP,28,42.0,False,False,False,14.0,39.8,55.0,43,55.8,1.15,9.26,39.5,-2.65,True,597.70,561.34,6.08,6.18,2.91,False,Stock,65.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.00pp),NaN,False
75,JSWSTEEL,UP,28,43.5,False,False,False,15.5,46.2,79.3,39,61.5,3.30,8.49,25.6,-4.36,True,1318.60,1265.27,4.04,1.43,0.60,False,Stock,75.9,NaN,NaN,False
76,KEI,UP,28,42.0,False,False,False,14.0,39.8,71.5,39,56.4,1.56,7.51,28.2,-6.62,True,5402.50,5350.29,0.97,-1.77,9.49,True,Stock,51.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 10.11pp),⚠ HIGH GAP RISK (>10.0%),False
77,TATAELXSI,UP,29,39.0,False,False,False,10.0,39.0,96.9,36,50.0,-0.05,9.70,55.6,1.08,False,3635.90,3530.45,2.90,-3.35,2.42,False,Stock,21.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 16.24pp),NaN,False
78,LT,UP,29,36.0,False,False,False,7.0,38.8,78.0,40,65.0,2.70,5.91,52.5,0.04,True,4017.50,3940.99,1.90,-0.19,2.19,False,Stock,83.8,NaN,NaN,False
79,INDIGO,UP,29,36.5,False,False,False,7.5,38.2,74.5,38,57.9,3.06,9.03,36.8,-2.46,True,5076.00,5010.89,1.28,-6.00,4.43,True,Stock,67.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.31pp),NaN,False
80,NATIONALUM,UP,29,36.5,False,False,False,7.5,33.8,63.2,45,51.1,2.53,10.31,33.3,-5.27,True,374.20,373.31,0.24,1.41,5.41,True,Stock,56.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.31pp),NaN,False
81,FINNIFTY,UP,29,33.5,False,False,False,4.5,30.2,73.3,46,63.0,2.36,3.37,43.5,-1.33,True,26030.90,25963.27,0.26,-3.53,1.47,False,Index,83.0,NaN,NaN,False
82,AUBANK,UP,29,55.0,False,False,False,26.0,58.5,87.9,24,70.8,4.54,6.31,58.3,1.06,True,1082.90,1053.42,2.72,2.16,1.21,False,Stock,74.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.94pp),NaN,False
83,APLAPOLLO,UP,29,53.0,False,False,False,24.0,80.5,112.5,29,58.6,3.41,6.87,41.4,-3.69,True,2239.20,2081.82,7.03,15.33,6.71,True,Stock,53.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 17.24pp),NaN,False
84,JINDALSTEL,UP,32,42.0,False,False,False,10.0,45.0,69.5,38,71.1,6.52,10.29,36.8,-2.78,True,1162.10,1106.25,4.81,5.42,0.80,False,Stock,78.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.48pp),NaN,False
85,ASHOKLEY,UP,32,42.0,False,False,False,10.0,31.0,76.3,40,57.5,1.11,8.21,37.5,-2.90,True,171.50,166.70,2.80,3.20,5.12,True,Stock,60.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.32pp),NaN,False
86,DABUR,DOWN,32,47.0,False,False,False,15.0,48.0,81.0,35,42.9,-1.52,11.63,52.8,1.84,False,386.00,402.12,4.18,8.41,-1.09,False,Stock,68.6,NaN,NaN,False
87,CHOLAFIN,UP,32,44.5,False,False,False,12.5,37.0,91.0,34,52.9,0.90,8.43,29.4,-3.10,True,1832.00,1764.62,3.68,-0.97,4.29,True,Stock,39.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 10.77pp),NaN,False
88,SIEMENS,UP,32,38.0,False,False,False,6.0,35.0,90.0,38,50.0,-0.08,7.22,36.8,-3.70,False,4065.00,3800.86,6.50,8.11,2.77,False,Stock,34.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.15pp),NaN,False
89,GMRAIRPORT,DOWN,33,42.0,False,False,False,9.0,39.0,72.4,39,41.0,-3.10,13.04,52.5,1.70,False,93.92,102.28,8.90,9.61,-2.98,False,Stock,54.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.07pp),NaN,False
90,PREMIERENE,DOWN,33,25.0,True,False,False,-8.0,38.0,62.6,7,NaN,NaN,NaN,NaN,NaN,None,1024.40,1088.46,6.25,-4.24,-5.16,True,Stock,None,None,None,True
91,WIPRO,UP,33,40.5,False,False,False,7.5,37.0,75.3,39,46.2,-0.74,7.04,43.6,-1.37,False,181.24,175.57,3.13,-2.73,1.48,False,Stock,37.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.28pp),NaN,False
92,KPITTECH,UP,34,38.5,False,False,False,4.5,40.5,78.5,23,39.1,-1.97,10.66,34.8,-5.68,False,589.55,564.48,4.25,-7.70,6.03,True,Stock,7.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 18.72pp),⚠ HIGH GAP RISK (>10.0%),False
93,UNOMINDA,UP,34,50.0,False,False,False,16.0,54.5,113.2,29,51.7,1.08,8.07,31.0,-3.70,True,1280.00,1211.39,5.36,9.52,0.41,False,Stock,31.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 15.29pp),⚠ HIGH GAP RISK (>10.0%),False
94,PHOENIXLTD,DOWN,34,63.0,False,False,False,29.0,85.5,160.0,23,43.5,-1.32,16.55,66.7,4.20,False,1891.20,1998.66,5.68,1.01,-5.57,True,Stock,70.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.70pp),NaN,False
95,ADANIPORTS,DOWN,34,49.0,False,False,False,15.0,33.0,67.8,36,38.9,-1.62,11.53,54.1,0.72,False,1647.50,1760.48,6.86,4.20,-3.10,False,Stock,46.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.52pp),NaN,False
96,CUMMINSIND,DOWN,34,52.0,False,False,False,18.0,46.0,102.6,32,40.6,-1.74,14.94,48.5,-0.22,False,5076.00,5408.15,6.54,5.70,-1.33,False,Stock,30.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.51pp),NaN,False
97,INDUSINDBK,DOWN,35,43.0,False,False,False,8.0,38.0,88.4,34,50.0,-0.36,44.67,54.3,0.52,False,993.60,1045.84,5.26,-0.17,-1.46,False,Stock,46.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.78pp),NaN,False
98,ONGC,DOWN,36,39.0,False,False,False,3.0,31.5,83.8,39,41.0,-1.79,18.39,52.5,0.20,False,235.27,242.97,3.27,1.38,-4.10,True,Stock,47.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.42pp),NaN,False
99,SAGILITY,UP,36,48.0,False,False,False,12.0,25.0,40.6,6,NaN,NaN,NaN,NaN,NaN,None,46.37,42.40,8.57,7.11,7.10,True,Stock,None,None,None,True
100,GODFRYPHLP,UP,36,48.5,False,False,False,12.5,48.8,80.0,35,54.3,2.46,11.04,45.7,-0.50,True,2095.00,2061.87,1.58,-5.23,3.80,False,Stock,43.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 10.70pp),NaN,False

In [ ]:
status_up = status[status["direction"] == "UP"].sort_values("trend_age_days", ascending=True).head(150).reset_index(drop=True)

print("SORTED BY: trend_age_days ascending — most recently flipped UP first")
status_up

SORTED BY: trend_age_days ascending — most recently flipped UP first

,symbol,direction,trend_age_days,median_duration,past_median,past_75th_pct,past_90th_pct,runway_left_vs_median,runway_left_vs_p75,runway_left_vs_p90,dir_flips,dir_win_rate,dir_median_move,worst_day,opp_win_rate,opp_median_move,signal_works_here,spot,flip_level,buffer_to_flip_pct,moved_since_entry_pct,entry_day_move,born_on_outlier_day,security_type,trend_score,outlier_reliance_flag,gap_risk_flag,thin_sample
0,OFSS,UP,1,46.0,False,False,False,45.0,78.2,126.9,34,41.2,-2.24,8.31,41.2,-1.16,False,12220.00,11257.20,7.88,-2.55,2.87,False,Stock,14.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 9.77pp),NaN,False
1,AXISBANK,UP,1,54.0,False,False,False,53.0,87.0,112.7,34,67.6,3.66,7.57,38.2,-1.36,True,1266.30,1209.49,4.49,-2.59,2.77,False,Stock,87.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.40pp),NaN,False
2,SUNPHARMA,UP,1,45.5,False,False,False,44.5,70.8,122.2,37,51.4,0.27,6.39,48.6,-0.18,True,1931.30,1839.93,4.73,-2.70,3.37,False,Stock,47.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.78pp),NaN,False
3,CGPOWER,UP,1,45.5,False,False,False,44.5,67.2,97.7,40,57.5,2.99,8.63,40.0,-2.53,True,885.95,827.70,6.57,-3.28,3.04,False,Stock,54.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 14.14pp),NaN,False
4,AMBER,UP,5,50.0,False,False,False,45.0,75.8,96.8,24,45.8,-1.18,10.28,50.0,-0.26,False,7582.50,7160.28,5.57,-1.54,3.15,False,Stock,15.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 15.92pp),⚠ HIGH GAP RISK (>10.0%),False
5,CDSL,UP,6,36.5,False,False,False,30.5,71.2,128.5,28,39.3,-3.49,9.99,46.4,-0.28,False,1386.90,1329.38,4.15,-3.28,2.81,False,Stock,5.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 15.71pp),NaN,False
6,MAHABANK,UP,6,41.0,False,False,False,35.0,58.2,103.5,38,47.4,-1.69,8.97,42.1,-2.36,False,82.85,78.51,5.24,-3.21,4.77,True,Stock,19.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.12pp),NaN,False
7,LICHSGFIN,UP,6,38.0,False,False,False,32.0,65.5,91.0,41,43.9,-0.29,9.49,48.8,-0.42,False,534.40,500.41,6.36,1.91,3.64,False,Stock,33.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.40pp),NaN,False
8,NMDC,UP,6,43.0,False,False,False,37.0,72.2,113.8,36,66.7,3.70,10.08,38.9,-4.27,True,85.96,81.41,5.30,-2.55,2.64,False,Stock,71.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.03pp),NaN,False
9,HDFCAMC,UP,7,33.5,False,False,False,26.5,56.8,102.3,29,48.3,-0.25,6.33,48.3,-0.84,False,2551.30,2517.52,1.32,-5.44,3.06,False,Stock,33.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.67pp),NaN,False
10,GLENMARK,UP,8,55.0,False,False,False,47.0,80.5,108.5,33,54.5,2.36,8.35,54.5,0.83,True,2485.80,2299.30,7.50,3.98,3.14,False,Stock,54.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.82pp),NaN,False
11,VMM,UP,8,52.0,False,False,False,44.0,91.2,127.1,4,NaN,NaN,NaN,NaN,NaN,None,108.04,101.93,5.66,-4.81,9.74,True,Stock,None,None,None,True
12,LICI,UP,11,37.0,False,False,False,26.0,86.2,98.3,14,50.0,-0.92,6.57,64.3,2.56,False,414.15,397.40,4.04,-1.92,0.78,False,Stock,None,None,None,True
13,PETRONET,UP,12,52.0,False,False,False,40.0,73.0,88.8,37,45.9,-0.09,5.77,35.1,-2.57,False,292.20,276.47,5.38,0.27,1.13,False,Stock,37.8,NaN,NaN,False
14,OBEROIRLTY,UP,15,49.5,False,False,False,34.5,68.8,138.0,31,64.5,2.78,11.57,32.3,-3.57,True,1879.20,1744.15,7.19,-2.68,4.60,True,Stock,65.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.25pp),NaN,False
15,MOTILALOFS,UP,15,54.0,False,False,False,39.0,73.0,109.4,32,62.5,3.04,8.08,43.8,-1.02,True,1027.00,953.06,7.20,7.54,5.68,True,Stock,55.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 11.86pp),⚠ HIGH GAP RISK (>10.0%),False
16,IDEA,UP,18,40.0,False,False,False,22.0,50.2,98.0,38,36.8,-4.23,16.25,57.9,4.96,False,14.18,13.81,2.64,0.50,4.44,True,Stock,3.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 12.23pp),NaN,False
17,BEL,UP,19,38.0,False,False,False,19.0,43.0,83.0,41,53.7,3.72,7.67,34.1,-4.01,True,412.15,394.10,4.38,0.40,1.18,False,Stock,70.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.72pp),NaN,False
18,FORCEMOT,UP,20,47.5,False,False,False,27.5,51.0,112.9,20,55.0,5.42,9.43,60.0,3.06,True,17874.00,17141.86,4.10,-7.24,5.12,True,Stock,50.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 20.35pp),NaN,False
19,POLICYBZR,UP,21,29.5,False,False,False,8.5,31.0,84.0,17,35.3,-5.87,13.34,41.2,-1.33,False,1845.30,1694.96,8.15,6.48,6.32,True,Stock,6.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.30pp),NaN,False
20,MCX,UP,21,39.0,False,False,False,18.0,50.2,99.5,38,42.1,-1.21,14.63,42.1,-1.39,False,3298.50,3054.57,7.40,13.94,4.92,True,Stock,12.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 11.18pp),NaN,False
21,POWERINDIA,UP,22,36.5,False,False,False,14.5,58.0,109.6,19,63.2,6.81,11.72,36.8,-5.14,True,32760.00,32116.12,1.97,-9.13,10.58,True,Stock,67.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 13.68pp),⚠ HIGH GAP RISK (>10.0%),False
22,VEDL,UP,25,50.0,False,False,False,25.0,52.0,94.5,37,64.9,3.60,14.11,35.1,-2.96,True,276.85,261.17,5.66,-0.72,1.40,False,Stock,65.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 10.76pp),⚠ HIGH GAP RISK (>10.0%),False
23,MAZDOCK,UP,26,33.5,False,False,False,7.5,39.2,64.9,21,57.1,3.70,10.89,38.1,-1.21,True,2486.70,2425.26,2.47,-1.71,6.28,True,Stock,54.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 18.99pp),NaN,False
24,COCHINSHIP,UP,26,49.5,False,False,False,23.5,58.0,83.4,27,44.4,-0.60,11.49,59.3,3.60,False,1482.50,1449.08,2.25,-0.50,4.56,True,Stock,23.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 16.75pp),⚠ HIGH GAP RISK (>10.0%),False
25,KOTAKBANK,UP,27,45.0,False,False,False,18.0,61.2,93.0,34,55.9,1.02,6.33,38.2,-1.41,True,425.85,401.57,5.70,6.46,0.50,False,Stock,64.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.61pp),NaN,False
26,NAM-INDIA,UP,27,50.5,False,False,False,23.5,59.2,133.6,20,55.0,0.73,7.74,45.0,-1.96,True,1182.80,1153.85,2.45,-2.65,1.08,False,Stock,34.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 15.51pp),⚠ HIGH GAP RISK (>10.0%),False
27,SAIL,UP,27,41.0,False,False,False,14.0,39.8,69.7,41,51.2,0.25,10.23,46.3,-0.89,True,194.05,176.96,8.81,10.57,1.12,False,Stock,30.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.77pp),NaN,False
28,TATASTEEL,UP,27,43.5,False,False,False,16.5,44.2,80.0,38,65.8,3.76,8.57,42.1,-1.62,True,185.04,180.25,2.59,-4.12,1.07,False,Stock,79.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.92pp),NaN,False
29,KEI,UP,28,42.0,False,False,False,14.0,39.8,71.5,39,56.4,1.56,7.51,28.2,-6.62,True,5402.50,5350.29,0.97,-1.77,9.49,True,Stock,51.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 10.11pp),⚠ HIGH GAP RISK (>10.0%),False
30,JSWSTEEL,UP,28,43.5,False,False,False,15.5,46.2,79.3,39,61.5,3.30,8.49,25.6,-4.36,True,1318.60,1265.27,4.04,1.43,0.60,False,Stock,75.9,NaN,NaN,False
31,HINDZINC,UP,28,42.0,False,False,False,14.0,39.8,55.0,43,55.8,1.15,9.26,39.5,-2.65,True,597.70,561.34,6.08,6.18,2.91,False,Stock,65.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.00pp),NaN,False
32,HINDALCO,UP,28,43.0,False,False,False,15.0,46.2,87.9,37,64.9,4.37,10.98,35.1,-2.35,True,1021.30,997.57,2.32,0.13,2.52,False,Stock,79.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.15pp),NaN,False
33,TATAELXSI,UP,29,39.0,False,False,False,10.0,39.0,96.9,36,50.0,-0.05,9.70,55.6,1.08,False,3635.90,3530.45,2.90,-3.35,2.42,False,Stock,21.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 16.24pp),NaN,False
34,LT,UP,29,36.0,False,False,False,7.0,38.8,78.0,40,65.0,2.70,5.91,52.5,0.04,True,4017.50,3940.99,1.90,-0.19,2.19,False,Stock,83.8,NaN,NaN,False
35,INDIGO,UP,29,36.5,False,False,False,7.5,38.2,74.5,38,57.9,3.06,9.03,36.8,-2.46,True,5076.00,5010.89,1.28,-6.00,4.43,True,Stock,67.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.31pp),NaN,False
36,NATIONALUM,UP,29,36.5,False,False,False,7.5,33.8,63.2,45,51.1,2.53,10.31,33.3,-5.27,True,374.20,373.31,0.24,1.41,5.41,True,Stock,56.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.31pp),NaN,False
37,FINNIFTY,UP,29,33.5,False,False,False,4.5,30.2,73.3,46,63.0,2.36,3.37,43.5,-1.33,True,26030.90,25963.27,0.26,-3.53,1.47,False,Index,83.0,NaN,NaN,False
38,AUBANK,UP,29,55.0,False,False,False,26.0,58.5,87.9,24,70.8,4.54,6.31,58.3,1.06,True,1082.90,1053.42,2.72,2.16,1.21,False,Stock,74.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.94pp),NaN,False
39,APLAPOLLO,UP,29,53.0,False,False,False,24.0,80.5,112.5,29,58.6,3.41,6.87,41.4,-3.69,True,2239.20,2081.82,7.03,15.33,6.71,True,Stock,53.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 17.24pp),NaN,False
40,JINDALSTEL,UP,32,42.0,False,False,False,10.0,45.0,69.5,38,71.1,6.52,10.29,36.8,-2.78,True,1162.10,1106.25,4.81,5.42,0.80,False,Stock,78.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.48pp),NaN,False
41,ASHOKLEY,UP,32,42.0,False,False,False,10.0,31.0,76.3,40,57.5,1.11,8.21,37.5,-2.90,True,171.50,166.70,2.80,3.20,5.12,True,Stock,60.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.32pp),NaN,False
42,CHOLAFIN,UP,32,44.5,False,False,False,12.5,37.0,91.0,34,52.9,0.90,8.43,29.4,-3.10,True,1832.00,1764.62,3.68,-0.97,4.29,True,Stock,39.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 10.77pp),NaN,False
43,SIEMENS,UP,32,38.0,False,False,False,6.0,35.0,90.0,38,50.0,-0.08,7.22,36.8,-3.70,False,4065.00,3800.86,6.50,8.11,2.77,False,Stock,34.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.15pp),NaN,False
44,WIPRO,UP,33,40.5,False,False,False,7.5,37.0,75.3,39,46.2,-0.74,7.04,43.6,-1.37,False,181.24,175.57,3.13,-2.73,1.48,False,Stock,37.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.28pp),NaN,False
45,UNOMINDA,UP,34,50.0,False,False,False,16.0,54.5,113.2,29,51.7,1.08,8.07,31.0,-3.70,True,1280.00,1211.39,5.36,9.52,0.41,False,Stock,31.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 15.29pp),⚠ HIGH GAP RISK (>10.0%),False
46,KPITTECH,UP,34,38.5,False,False,False,4.5,40.5,78.5,23,39.1,-1.97,10.66,34.8,-5.68,False,589.55,564.48,4.25,-7.70,6.03,True,Stock,7.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 18.72pp),⚠ HIGH GAP RISK (>10.0%),False
47,SAGILITY,UP,36,48.0,False,False,False,12.0,25.0,40.6,6,NaN,NaN,NaN,NaN,NaN,None,46.37,42.40,8.57,7.11,7.10,True,Stock,None,None,None,True
48,GODFRYPHLP,UP,36,48.5,False,False,False,12.5,48.8,80.0,35,54.3,2.46,11.04,45.7,-0.50,True,2095.00,2061.87,1.58,-5.23,3.80,False,Stock,43.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 10.70pp),NaN,False
49,ASTRAL,UP,39,50.0,False,False,False,11.0,46.0,87.2,32,65.6,3.46,7.25,50.0,0.43,True,1510.50,1448.71,4.09,2.89,3.87,False,Stock,73.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.26pp),NaN,False
50,EICHERMOT,UP,42,31.0,True,False,False,-11.0,19.0,56.2,45,51.1,0.03,7.05,35.6,-2.76,True,7927.00,7716.97,2.65,3.09,1.67,False,Stock,43.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.44pp),NaN,False
51,SOLARINDS,UP,43,52.0,False,False,False,9.0,62.5,89.0,29,55.2,4.19,6.98,34.5,-2.80,True,20130.00,18897.26,6.12,5.79,3.04,False,Stock,57.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 9.88pp),⚠ HIGH GAP RISK (>10.0%),False
52,OIL,UP,43,58.0,False,False,False,15.0,43.8,86.7,31,54.8,1.66,9.62,58.1,3.35,True,490.70,450.58,8.18,8.19,4.18,True,Stock,57.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.11pp),NaN,False
53,PNB,UP,43,37.0,True,False,False,-6.0,13.0,48.0,45,44.4,-1.47,10.70,44.4,-0.91,False,116.03,112.09,3.39,3.82,5.66,True,Stock,24.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.56pp),NaN,False
54,BIOCON,UP,47,42.5,True,False,False,-4.5,29.2,64.5,38,52.6,0.15,6.06,34.2,-2.16,True,402.80,401.75,0.26,-8.60,1.40,False,Stock,38.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.23pp),NaN,False
55,BHEL,UP,48,42.5,True,False,False,-5.5,21.0,53.1,40,65.0,2.33,11.55,57.5,3.28,True,426.20,398.30,6.55,1.97,3.48,False,Stock,62.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.75pp),NaN,False
56,SUPREMEIND,UP,48,53.0,False,False,False,5.0,34.8,70.7,30,63.3,2.14,9.48,56.7,0.40,True,3580.60,3395.58,5.17,3.55,0.88,False,Stock,66.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.17pp),NaN,False
57,BAJAJ-AUTO,UP,50,42.0,True,False,False,-8.0,24.0,60.0,38,55.3,0.56,7.01,36.8,-1.58,True,12356.00,11615.40,5.99,19.03,2.22,False,Stock,58.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.37pp),NaN,False
58,UNIONBANK,UP,50,35.5,True,False,False,-14.5,6.0,55.5,43,51.2,0.16,9.76,41.9,-0.64,True,184.84,176.17,4.69,8.48,3.57,False,Stock,32.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.65pp),NaN,False
59,INFY,UP,50,41.0,True,False,False,-9.0,16.5,53.9,39,51.3,0.34,6.04,41.0,-1.28,True,1149.70,1099.42,4.37,4.27,3.24,False,Stock,50.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.41pp),NaN,False
60,TECHM,UP,50,48.0,True,False,False,-2.0,25.0,89.0,33,51.5,0.62,7.34,48.5,-0.63,True,1643.60,1532.24,6.78,9.25,3.42,False,Stock,46.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.47pp),NaN,False
61,LTM,UP,53,45.5,True,False,False,-7.5,17.0,65.1,32,53.1,1.28,7.80,50.0,0.44,True,4627.80,4370.38,5.56,14.63,4.74,True,Stock,54.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.81pp),NaN,False
62,INDIANB,UP,53,44.0,True,False,False,-9.0,14.0,61.7,36,50.0,1.27,13.28,50.0,0.14,True,885.40,837.59,5.40,1.69,9.78,True,Stock,32.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 9.26pp),NaN,False
63,PERSISTENT,UP,53,41.0,True,False,False,-12.0,13.0,71.3,34,61.8,2.69,7.56,52.9,0.35,True,5764.50,5358.38,7.05,14.06,4.64,True,Stock,58.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 11.14pp),NaN,False
64,MPHASIS,UP,56,41.0,True,False,False,-15.0,21.2,51.4,29,41.4,-2.24,9.10,37.9,-4.50,False,2509.90,2307.15,8.08,8.53,2.92,False,Stock,8.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 17.21pp),NaN,False
65,JUBLFOOD,UP,56,49.0,True,False,False,-7.0,17.0,63.2,35,51.4,0.77,10.66,54.3,1.69,True,486.05,467.58,3.80,6.84,3.81,False,Stock,41.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.66pp),NaN,False
66,HCLTECH,UP,56,48.0,True,False,False,-8.0,24.5,63.3,34,58.8,0.97,5.95,41.2,-2.38,True,1365.00,1269.54,6.99,16.85,3.00,False,Stock,66.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.74pp),NaN,False
67,SWIGGY,UP,56,113.5,False,False,False,57.5,81.2,88.5,3,NaN,NaN,NaN,NaN,NaN,None,277.50,263.27,5.13,4.22,7.21,True,Stock,None,None,None,True
68,NESTLEIND,UP,57,47.5,True,False,False,-9.5,33.8,70.5,33,57.6,2.99,5.44,39.4,-1.62,True,1444.60,1427.21,1.20,-1.97,0.95,False,Stock,79.4,NaN,NaN,False
69,PNBHOUSING,UP,61,45.0,True,False,False,-16.0,25.0,73.5,28,57.1,7.52,7.92,53.6,2.35,True,1147.80,1100.88,4.09,8.73,0.36,False,Stock,69.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.12pp),NaN,False
70,PAYTM,UP,62,48.0,True,False,False,-14.0,16.0,44.9,14,57.1,5.97,8.10,50.0,0.48,True,1643.90,1564.85,4.81,36.57,5.45,True,Stock,None,None,None,True
71,LODHA,UP,68,38.0,True,False,False,-30.0,1.0,47.1,17,52.9,1.26,9.06,52.9,0.69,True,1206.40,1173.82,2.70,27.33,1.02,False,Stock,39.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.75pp),NaN,False
72,TVSMOTOR,UP,68,47.5,True,False,False,-20.5,13.2,73.2,29,58.6,3.85,7.45,44.8,-2.03,True,4273.30,4223.03,1.18,19.71,3.75,False,Stock,61.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 9.29pp),NaN,False
73,AUROPHARMA,UP,70,42.0,True,False,False,-28.0,5.0,45.9,34,47.1,-0.62,6.92,44.1,-0.62,False,1692.00,1572.10,7.09,10.29,2.84,False,Stock,24.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 10.78pp),NaN,False
74,HAL,UP,71,36.0,True,True,False,-35.0,-10.8,25.3,32,56.2,0.14,5.51,50.0,-0.24,True,4805.10,4742.08,1.31,6.42,2.43,False,Stock,43.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 11.36pp),NaN,False
75,MIDCPNIFTY,UP,75,15.0,True,True,True,-60.0,-48.0,-26.0,91,65.9,2.11,4.91,42.9,-0.45,True,14868.50,14650.35,1.47,1.87,0.14,False,Index,84.7,NaN,NaN,False
76,UNITDSPR,UP,75,47.0,True,False,False,-28.0,3.5,33.4,36,52.8,0.70,6.59,50.0,-0.02,True,1481.50,1469.73,0.79,9.72,3.23,False,Stock,52.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.62pp),NaN,False
77,NIFTY,UP,76,30.5,True,True,False,-45.5,-20.8,15.0,46,60.9,1.28,5.74,41.3,-0.63,True,24059.60,23990.87,0.29,-0.11,0.40,False,Index,76.8,NaN,NaN,False
78,KFINTECH,UP,76,45.0,True,True,False,-31.0,-23.2,20.1,11,54.5,2.20,8.35,45.5,-1.11,True,943.20,889.65,5.68,4.98,4.26,True,Stock,None,None,None,True
79,ICICIPRULI,UP,76,50.0,True,True,False,-26.0,-1.8,63.0,28,50.0,0.39,6.85,64.3,1.34,True,502.00,485.43,3.30,-0.33,2.71,False,Stock,37.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.46pp),NaN,False
80,PGEL,UP,77,35.0,True,True,False,-42.0,-13.8,50.0,36,52.8,0.09,16.94,50.0,0.11,True,571.10,559.05,2.11,8.28,7.03,True,Stock,21.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 25.41pp),⚠ HIGH GAP RISK (>10.0%),False
81,TITAN,UP,77,41.0,True,False,False,-36.0,0.8,37.4,35,62.9,4.65,6.73,37.1,-2.58,True,5048.50,4928.12,2.38,16.38,1.27,False,Stock,83.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.74pp),NaN,False
82,SENSEX,UP,77,30.0,True,True,False,-47.0,-23.0,13.6,49,59.2,1.32,5.94,40.8,-0.59,True,76987.09,76654.85,0.43,0.23,0.71,False,Index,77.0,NaN,NaN,False
83,GODREJPROP,UP,77,36.0,True,True,False,-41.0,-14.0,41.5,40,52.5,0.45,12.40,45.0,-1.82,True,1974.30,1957.99,0.83,10.02,1.60,False,Stock,41.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.05pp),⚠ HIGH GAP RISK (>10.0%),False
84,BAJAJFINSV,UP,77,51.0,True,False,False,-26.0,12.0,36.3,34,58.8,3.96,6.00,38.2,-1.28,True,1976.10,1953.53,1.14,10.56,2.12,False,Stock,74.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.53pp),NaN,False
85,PRESTIGE,UP,78,49.0,True,True,False,-29.0,-1.8,20.0,33,54.5,2.76,12.88,36.4,-3.73,True,1570.40,1541.50,1.84,6.65,6.14,True,Stock,50.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.16pp),NaN,False
86,KALYANKJIL,UP,78,32.0,True,True,False,-46.0,-15.5,34.1,19,52.6,1.00,7.42,31.6,-3.50,True,577.50,564.94,2.17,50.78,11.09,True,Stock,36.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 9.89pp),NaN,False
87,DLF,UP,78,40.0,True,True,False,-38.0,-2.8,33.0,38,50.0,0.18,8.49,50.0,-0.68,True,674.35,638.62,5.30,9.75,4.67,True,Stock,27.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.06pp),NaN,False
88,SHRIRAMFIN,UP,78,42.0,True,True,False,-36.0,-18.2,27.7,41,51.2,0.83,14.59,41.5,-1.76,True,1061.80,1059.73,0.20,6.11,4.79,True,Stock,42.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.39pp),NaN,False
89,BPCL,UP,78,41.0,True,True,False,-37.0,-13.2,20.0,41,56.1,0.73,8.06,36.6,-2.28,True,319.10,304.01,4.73,2.74,2.73,False,Stock,58.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.48pp),NaN,False
90,IOC,UP,78,35.0,True,True,False,-43.0,-15.8,21.1,42,52.4,0.34,7.82,40.5,-1.50,True,136.98,135.43,1.13,-5.20,2.52,False,Stock,43.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.30pp),NaN,False
91,SBIN,UP,81,39.5,True,True,False,-41.5,-18.8,9.0,44,63.6,2.06,7.39,38.6,-1.66,True,1033.90,1033.49,0.04,1.65,1.64,False,Stock,79.1,NaN,NaN,False
92,BANKNIFTY,UP,81,35.5,True,True,True,-45.5,-21.0,-4.1,46,54.3,0.56,4.78,37.0,-0.94,True,57452.30,56380.40,1.87,1.12,2.97,False,Index,61.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.07pp),NaN,False
93,ICICIBANK,UP,82,33.0,True,True,False,-49.0,-21.5,14.5,44,45.5,-0.40,7.46,27.3,-2.53,False,1430.80,1386.30,3.11,8.64,1.83,False,Stock,39.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.27pp),NaN,False
94,BANKINDIA,UP,84,36.0,True,True,False,-48.0,-20.2,11.5,40,35.0,-2.25,9.50,60.0,2.24,False,142.70,136.91,4.06,-3.40,5.45,True,Stock,11.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.03pp),NaN,False
95,NAUKRI,UP,91,39.0,True,False,False,-52.0,1.2,40.4,32,43.8,-0.98,8.21,28.1,-4.12,False,1363.60,1255.90,7.90,34.25,1.16,False,Stock,16.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.73pp),NaN,False
96,ABB,UP,97,46.5,True,True,False,-50.5,-16.0,11.9,35,51.4,2.49,7.32,40.0,-0.52,True,7432.50,7145.20,3.87,2.96,6.10,True,Stock,54.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.37pp),NaN,False
97,GAIL,UP,99,48.0,True,True,False,-51.0,-22.8,5.5,38,52.6,0.60,8.85,39.5,-1.70,True,172.77,165.79,4.04,2.43,4.91,True,Stock,51.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.46pp),NaN,False
98,DIXON,UP,102,38.0,True,True,False,-64.0,-19.0,25.0,27,70.4,6.10,8.95,48.1,-1.11,True,14647.00,13697.55,6.48,24.95,4.12,True,Stock,67.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 11.57pp),NaN,False
99,COFORGE,UP,116,55.5,True,True,False,-60.5,-28.0,33.3,30,70.0,8.66,8.08,50.0,0.18,True,1989.80,1843.16,7.37,45.44,6.44,True,Stock,73.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.09pp),⚠ HIGH GAP RISK (>10.0%),False
100,TORNTPHARM,UP,116,57.5,True,True,False,-58.5,-14.0,22.3,29,58.6,2.54,6.93,27.6,-3.19,True,4956.50,4705.97,5.05,13.14,0.41,False,Stock,73.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.85pp),NaN,False
101,CIPLA,UP,131,38.5,True,True,False,-92.5,-32.8,29.0,32,62.5,0.94,7.22,43.8,-1.18,True,1411.00,1391.45,1.39,8.05,5.63,True,Stock,69.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.34pp),NaN,False

## Top 25 UP-trending, ranked by trend_score (best first)

Sorted by score, not age — a fresh flip isn't automatically the best pick, and this is the view meant to answer that question directly when several instruments flip UP the same day. `trend_age_days` is still shown for context. Thin-sample names (score is blank) are included but sort to the bottom, not silently dropped.

## Good buy candidates today — the actual daily shortlist

Requires `signal_works_here == True` explicitly — UP has to have
HISTORICALLY WORKED on that specific instrument, not merely be the direction
currently showing. That is the one column from this session's work that
separates a real signal from noise (see the column reference at the top:
DOWN flips work on only 14% of this universe, UP on 68% — but even within
UP, `signal_works_here` still filters out the instruments where it does not
hold). Trend age is NOT part of the filter — a trend that flipped three
weeks ago and is still intact is just as buyable as one from yesterday
(`reversion_test.py`/`exhaustion_test.py` found age doesn't predict anything).

`thin_sample` names (fewer than 15 UP-closed flips → no `trend_score`)
are excluded here rather than sorted to the bottom — with no score, there's no
ranking basis, and this is meant to be a clean go-to list, not a place to
present unranked guesses next to ranked ones.

In [ ]:
good_buy_cols = ["symbol", "security_type", "trend_age_days", "trend_score", "dir_win_rate",
                  "dir_median_move", "buffer_to_flip_pct", "moved_since_entry_pct",
                  "worst_day", "outlier_reliance_flag", "gap_risk_flag"]

good_buy_candidates = status[
    (status["direction"] == "UP") &
    (status["signal_works_here"] == True) &
    (status["thin_sample"] == False)
].sort_values("trend_score", ascending=False)[good_buy_cols].reset_index(drop=True)

print(f"{len(good_buy_candidates)} instrument(s) — UP, signal historically works here, ranked")
print("SORTED BY: trend_score descending")
good_buy_candidates

86 instrument(s) — UP, signal historically works here, ranked
SORTED BY: trend_score descending

        symbol security_type  trend_age_days trend_score  dir_win_rate  dir_median_move  buffer_to_flip_pct  moved_since_entry_pct  worst_day                              outlier_reliance_flag             gap_risk_flag
0     AXISBANK         Stock               1                87.8          67.6             3.66                4.49                  -2.59       7.57   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.40pp)                       NaN
1   BAJAJHLDNG         Stock             146                87.1          70.0             4.10                4.95                  14.05       7.45   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.85pp)                       NaN
2   MIDCPNIFTY         Index              75                84.7          65.9             2.11                1.47                   1.87       4.91                                                NaN                       NaN
3           LT         Stock              29                83.8          65.0             2.70                1.90                  -0.19       5.91                                                NaN                       NaN
4        TITAN         Stock              77                83.4          62.9             4.65                2.38                  16.38       6.73   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.74pp)                       NaN
5     FINNIFTY         Index              29                83.0          63.0             2.36                0.26                  -3.53       3.37                                                NaN                       NaN
6     BOSCHLTD         Stock             152                81.6          64.5             3.40                4.41                  50.02       5.89                                                NaN                       NaN
7    TATASTEEL         Stock              27                79.6          65.8             3.76                2.59                  -4.12       8.57   ⚠ RELIES ON OUTLIER WINS (avg-median gap 5.92pp)                       NaN
8     HINDALCO         Stock              28                79.5          64.9             4.37                2.32                   0.13      10.98   ⚠ RELIES ON OUTLIER WINS (avg-median gap 5.15pp)                       NaN
9    NESTLEIND         Stock              57                79.4          57.6             2.99                1.20                  -1.97       5.44                                                NaN                       NaN
10        SBIN         Stock              81                79.1          63.6             2.06                0.04                   1.65       7.39                                                NaN                       NaN
11  JINDALSTEL         Stock              32                78.7          71.1             6.52                4.81                   5.42      10.29   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.48pp)                       NaN
12      SENSEX         Index              77                77.0          59.2             1.32                0.43                   0.23       5.94                                                NaN                       NaN
13       NIFTY         Index              76                76.8          60.9             1.28                0.29                  -0.11       5.74                                                NaN                       NaN
14    JSWSTEEL         Stock              28                75.9          61.5             3.30                4.04                   1.43       8.49                                                NaN                       NaN
15      RADICO         Stock             174                74.3          72.4             7.59                1.06                  53.71      10.66   ⚠ RELIES ON OUTLIER WINS (avg-median gap 7.16pp)  ⚠ HIGH GAP RISK (>10.0%)
16  BAJAJFINSV         Stock              77                74.2          58.8             3.96                1.14                  10.56       6.00   ⚠ RELIES ON OUTLIER WINS (avg-median gap 8.53pp)                       NaN
17      AUBANK         Stock              29                74.2          70.8             4.54                2.72                   2.16       6.31   ⚠ RELIES ON OUTLIER WINS (avg-median gap 7.94pp)                       NaN
18      ASTRAL         Stock              39                73.5          65.6             3.46                4.09                   2.89       7.25   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.26pp)                       NaN
19     COFORGE         Stock             116                73.4          70.0             8.66                7.37                  45.44       8.08   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.09pp)  ⚠ HIGH GAP RISK (>10.0%)
20  TORNTPHARM         Stock             116                73.0          58.6             2.54                5.05                  13.14       6.93   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.85pp)                       NaN
21        NMDC         Stock               6                71.4          66.7             3.70                5.30                  -2.55      10.08   ⚠ RELIES ON OUTLIER WINS (avg-median gap 8.03pp)                       NaN
22         BEL         Stock              19                70.0          53.7             3.72                4.38                   0.40       7.67   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.72pp)                       NaN
23  PNBHOUSING         Stock              61                69.5          57.1             7.52                4.09                   8.73       7.92   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.12pp)                       NaN
24       CIPLA         Stock             131                69.1          62.5             0.94                1.39                   8.05       7.22   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.34pp)                       NaN
25       DIXON         Stock             102                67.7          70.4             6.10                6.48                  24.95       8.95  ⚠ RELIES ON OUTLIER WINS (avg-median gap 11.57pp)                       NaN
26      INDIGO         Stock              29                67.6          57.9             3.06                1.28                  -6.00       9.03   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.31pp)                       NaN
27  POWERINDIA         Stock              22                67.5          63.2             6.81                1.97                  -9.13      11.72  ⚠ RELIES ON OUTLIER WINS (avg-median gap 13.68pp)  ⚠ HIGH GAP RISK (>10.0%)
28     HCLTECH         Stock              56                66.8          58.8             0.97                6.99                  16.85       5.95   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.74pp)                       NaN
29  PIDILITIND         Stock             133                66.5          52.8             1.35                2.88                  17.11       6.71                                                NaN                       NaN
30  SUPREMEIND         Stock              48                66.0          63.3             2.14                5.17                   3.55       9.48   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.17pp)                       NaN
31    HINDZINC         Stock              28                65.7          55.8             1.15                6.08                   6.18       9.26   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.00pp)                       NaN
32        VEDL         Stock              25                65.1          64.9             3.60                5.66                  -0.72      14.11  ⚠ RELIES ON OUTLIER WINS (avg-median gap 10.76pp)  ⚠ HIGH GAP RISK (>10.0%)
33  OBEROIRLTY         Stock              15                65.1          64.5             2.78                7.19                  -2.68      11.57   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.25pp)                       NaN
34   KOTAKBANK         Stock              27                64.8          55.9             1.02                5.70                   6.46       6.33   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.61pp)                       NaN
35      GRASIM         Stock             133                64.6          61.1             0.75                6.10                  18.90       7.72   ⚠ RELIES ON OUTLIER WINS (avg-median gap 5.71pp)                       NaN
36      360ONE         Stock             139                63.1          66.7             3.96                3.45                   9.95      10.92  ⚠ RELIES ON OUTLIER WINS (avg-median gap 26.98pp)  ⚠ HIGH GAP RISK (>10.0%)
37        BHEL         Stock              48                62.7          65.0             2.33                6.55                   1.97      11.55   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.75pp)                       NaN
38   BANKNIFTY         Index              81                61.7          54.3             0.56                1.87                   1.12       4.78   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.07pp)                       NaN
39    TVSMOTOR         Stock              68                61.6          58.6             3.85                1.18                  19.71       7.45   ⚠ RELIES ON OUTLIER WINS (avg-median gap 9.29pp)                       NaN
40    ASHOKLEY         Stock              32                60.1          57.5             1.11                2.80                   3.20       8.21   ⚠ RELIES ON OUTLIER WINS (avg-median gap 5.32pp)                       NaN
41  BAJAJ-AUTO         Stock              50                58.9          55.3             0.56                5.99                  19.03       7.01   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.37pp)                       NaN
42        BPCL         Stock              78                58.6          56.1             0.73                4.73                   2.74       8.06   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.48pp)                       NaN
43  PERSISTENT         Stock              53                58.4          61.8             2.69                7.05                  14.06       7.56  ⚠ RELIES ON OUTLIER WINS (avg-median gap 11.14pp)                       NaN
44   SOLARINDS         Stock              43                57.7          55.2             4.19                6.12                   5.79       6.98   ⚠ RELIES ON OUTLIER WINS (avg-median gap 9.88pp)  ⚠ HIGH GAP RISK (>10.0%)
45         OIL         Stock              43                57.5          54.8             1.66                8.18                   8.19       9.62   ⚠ RELIES ON OUTLIER WINS (avg-median gap 8.11pp)                       NaN
46    DIVISLAB         Stock             138                56.8          54.3             1.74                4.75                  45.55      11.39   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.51pp)                       NaN
47  NATIONALUM         Stock              29                56.7          51.1             2.53                0.24                   1.41      10.31   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.31pp)                       NaN
48  MOTILALOFS         Stock              15                55.6          62.5             3.04                7.20                   7.54       8.08  ⚠ RELIES ON OUTLIER WINS (avg-median gap 11.86pp)  ⚠ HIGH GAP RISK (>10.0%)
49     CGPOWER         Stock               1                54.7          57.5             2.99                6.57                  -3.28       8.63  ⚠ RELIES ON OUTLIER WINS (avg-median gap 14.14pp)                       NaN
50         LTM         Stock              53                54.4          53.1             1.28                5.56                  14.63       7.80   ⚠ RELIES ON OUTLIER WINS (avg-median gap 7.81pp)                       NaN
51     MAZDOCK         Stock              26                54.4          57.1             3.70                2.47                  -1.71      10.89  ⚠ RELIES ON OUTLIER WINS (avg-median gap 18.99pp)                       NaN
52    GLENMARK         Stock               8                54.4          54.5             2.36                7.50                   3.98       8.35   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.82pp)                       NaN
53         ABB         Stock              97                54.1          51.4             2.49                3.87                   2.96       7.32   ⚠ RELIES ON OUTLIER WINS (avg-median gap 5.37pp)                       NaN
54   APLAPOLLO         Stock              29                53.3          58.6             3.41                7.03                  15.33       6.87  ⚠ RELIES ON OUTLIER WINS (avg-median gap 17.24pp)                       NaN
55    UNITDSPR         Stock              75                52.4          52.8             0.70                0.79                   9.72       6.59   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.62pp)                       NaN
56         KEI         Stock              28                51.5          56.4             1.56                0.97                  -1.77       7.51  ⚠ RELIES ON OUTLIER WINS (avg-median gap 10.11pp)  ⚠ HIGH GAP RISK (>10.0%)
57        GAIL         Stock              99                51.1          52.6             0.60                4.04                   2.43       8.85   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.46pp)                       NaN
58    PRESTIGE         Stock              78                50.1          54.5             2.76                1.84                   6.65      12.88   ⚠ RELIES ON OUTLIER WINS (avg-median gap 7.16pp)                       NaN
59    FORCEMOT         Stock              20                50.1          55.0             5.42                4.10                  -7.24       9.43  ⚠ RELIES ON OUTLIER WINS (avg-median gap 20.35pp)                       NaN
60        INFY         Stock              50                50.0          51.3             0.34                4.37                   4.27       6.04   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.41pp)                       NaN
61  FEDERALBNK         Stock             144                49.1          54.8             0.36                2.09                  20.09       8.52   ⚠ RELIES ON OUTLIER WINS (avg-median gap 5.11pp)                       NaN
62   SUNPHARMA         Stock               1                47.7          51.4             0.27                4.73                  -2.70       6.39   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.78pp)                       NaN
63       TECHM         Stock              50                46.7          51.5             0.62                6.78                   9.25       7.34   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.47pp)                       NaN
64   MOTHERSON         Stock             144                46.3          55.3             0.55                4.27                  35.52      15.06   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.12pp)                       NaN
65         HAL         Stock              71                43.9          56.2             0.14                1.31                   6.42       5.51  ⚠ RELIES ON OUTLIER WINS (avg-median gap 11.36pp)                       NaN
66   EICHERMOT         Stock              42                43.8          51.1             0.03                2.65                   3.09       7.05   ⚠ RELIES ON OUTLIER WINS (avg-median gap 3.44pp)                       NaN
67         IOC         Stock              78                43.7          52.4             0.34                1.13                  -5.20       7.82   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.30pp)                       NaN
68  GODFRYPHLP         Stock              36                43.4          54.3             2.46                1.58                  -5.23      11.04  ⚠ RELIES ON OUTLIER WINS (avg-median gap 10.70pp)                       NaN
69  SHRIRAMFIN         Stock              78                42.6          51.2             0.83                0.20                   6.11      14.59   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.39pp)                       NaN
70    JUBLFOOD         Stock              56                41.9          51.4             0.77                3.80                   6.84      10.66   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.66pp)                       NaN
71  GODREJPROP         Stock              77                41.6          52.5             0.45                0.83                  10.02      12.40   ⚠ RELIES ON OUTLIER WINS (avg-median gap 7.05pp)  ⚠ HIGH GAP RISK (>10.0%)
72       LODHA         Stock              68                39.9          52.9             1.26                2.70                  27.33       9.06   ⚠ RELIES ON OUTLIER WINS (avg-median gap 7.75pp)                       NaN
73    CHOLAFIN         Stock              32                39.8          52.9             0.90                3.68                  -0.97       8.43  ⚠ RELIES ON OUTLIER WINS (avg-median gap 10.77pp)                       NaN
74   ZYDUSLIFE         Stock             139                39.6          51.5             0.03                6.99                  25.31       6.76   ⚠ RELIES ON OUTLIER WINS (avg-median gap 5.73pp)                       NaN
75      BIOCON         Stock              47                38.6          52.6             0.15                0.26                  -8.60       6.06   ⚠ RELIES ON OUTLIER WINS (avg-median gap 5.23pp)                       NaN
76  ICICIPRULI         Stock              76                37.9          50.0             0.39                3.30                  -0.33       6.85   ⚠ RELIES ON OUTLIER WINS (avg-median gap 6.46pp)                       NaN
77  KALYANKJIL         Stock              78                36.2          52.6             1.00                2.17                  50.78       7.42   ⚠ RELIES ON OUTLIER WINS (avg-median gap 9.89pp)                       NaN
78   NAM-INDIA         Stock              27                34.3          55.0             0.73                2.45                  -2.65       7.74  ⚠ RELIES ON OUTLIER WINS (avg-median gap 15.51pp)  ⚠ HIGH GAP RISK (>10.0%)
79     INDIANB         Stock              53                32.6          50.0             1.27                5.40                   1.69      13.28   ⚠ RELIES ON OUTLIER WINS (avg-median gap 9.26pp)                       NaN
80   UNIONBANK         Stock              50                32.1          51.2             0.16                4.69                   8.48       9.76   ⚠ RELIES ON OUTLIER WINS (avg-median gap 4.65pp)                       NaN
81    UNOMINDA         Stock              34                31.4          51.7             1.08                5.36                   9.52       8.07  ⚠ RELIES ON OUTLIER WINS (avg-median gap 15.29pp)  ⚠ HIGH GAP RISK (>10.0%)
82        SAIL         Stock              27                30.7          51.2             0.25                8.81                  10.57      10.23   ⚠ RELIES ON OUTLIER WINS (avg-median gap 7.77pp)                       NaN
83   HINDPETRO         Stock             134                28.5          51.3             0.38                1.19                   0.64       8.61   ⚠ RELIES ON OUTLIER WINS (avg-median gap 8.00pp)                       NaN
84         DLF         Stock              78                27.4          50.0             0.18                5.30                   9.75       8.49   ⚠ RELIES ON OUTLIER WINS (avg-median gap 8.06pp)                       NaN
85        PGEL         Stock              77                21.9          52.8             0.09                2.11                   8.28      16.94  ⚠ RELIES ON OUTLIER WINS (avg-median gap 25.41pp)  ⚠ HIGH GAP RISK (>10.0%)

### Top 25 UP-trending, ranked by score

In [ ]:
top25_up = status_up[status_up["direction"] == "UP"].sort_values(
    "trend_score", ascending=False, na_position="last"
).head(25)
print("SORTED BY: trend_score descending, thin-sample (blank score) last")
top25_up

SORTED BY: trend_score descending, thin-sample (blank score) last

,symbol,direction,trend_age_days,median_duration,past_median,past_75th_pct,past_90th_pct,runway_left_vs_median,runway_left_vs_p75,runway_left_vs_p90,dir_flips,dir_win_rate,dir_median_move,worst_day,opp_win_rate,opp_median_move,signal_works_here,spot,flip_level,buffer_to_flip_pct,moved_since_entry_pct,entry_day_move,born_on_outlier_day,security_type,trend_score,outlier_reliance_flag,gap_risk_flag,thin_sample
1,AXISBANK,UP,1,54.0,False,False,False,53.0,87.0,112.7,34,67.6,3.66,7.57,38.2,-1.36,True,1266.30,1209.49,4.49,-2.59,2.77,False,Stock,87.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.40pp),NaN,False
116,BAJAJHLDNG,UP,146,59.5,True,True,True,-86.5,-55.0,-10.7,30,70.0,4.10,7.45,46.7,-0.92,True,11371.00,10807.72,4.95,14.05,7.94,True,Stock,87.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.85pp),NaN,False
75,MIDCPNIFTY,UP,75,15.0,True,True,True,-60.0,-48.0,-26.0,91,65.9,2.11,4.91,42.9,-0.45,True,14868.50,14650.35,1.47,1.87,0.14,False,Index,84.7,NaN,NaN,False
34,LT,UP,29,36.0,False,False,False,7.0,38.8,78.0,40,65.0,2.70,5.91,52.5,0.04,True,4017.50,3940.99,1.90,-0.19,2.19,False,Stock,83.8,NaN,NaN,False
81,TITAN,UP,77,41.0,True,False,False,-36.0,0.8,37.4,35,62.9,4.65,6.73,37.1,-2.58,True,5048.50,4928.12,2.38,16.38,1.27,False,Stock,83.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.74pp),NaN,False
37,FINNIFTY,UP,29,33.5,False,False,False,4.5,30.2,73.3,46,63.0,2.36,3.37,43.5,-1.33,True,26030.90,25963.27,0.26,-3.53,1.47,False,Index,83.0,NaN,NaN,False
120,BOSCHLTD,UP,152,45.5,True,True,True,-106.5,-65.0,-20.6,31,64.5,3.40,5.89,64.5,1.91,True,48210.00,46082.99,4.41,50.02,4.90,True,Stock,81.6,NaN,NaN,False
28,TATASTEEL,UP,27,43.5,False,False,False,16.5,44.2,80.0,38,65.8,3.76,8.57,42.1,-1.62,True,185.04,180.25,2.59,-4.12,1.07,False,Stock,79.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.92pp),NaN,False
32,HINDALCO,UP,28,43.0,False,False,False,15.0,46.2,87.9,37,64.9,4.37,10.98,35.1,-2.35,True,1021.30,997.57,2.32,0.13,2.52,False,Stock,79.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.15pp),NaN,False
68,NESTLEIND,UP,57,47.5,True,False,False,-9.5,33.8,70.5,33,57.6,2.99,5.44,39.4,-1.62,True,1444.60,1427.21,1.20,-1.97,0.95,False,Stock,79.4,NaN,NaN,False
91,SBIN,UP,81,39.5,True,True,False,-41.5,-18.8,9.0,44,63.6,2.06,7.39,38.6,-1.66,True,1033.90,1033.49,0.04,1.65,1.64,False,Stock,79.1,NaN,NaN,False
40,JINDALSTEL,UP,32,42.0,False,False,False,10.0,45.0,69.5,38,71.1,6.52,10.29,36.8,-2.78,True,1162.10,1106.25,4.81,5.42,0.80,False,Stock,78.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.48pp),NaN,False
82,SENSEX,UP,77,30.0,True,True,False,-47.0,-23.0,13.6,49,59.2,1.32,5.94,40.8,-0.59,True,76987.09,76654.85,0.43,0.23,0.71,False,Index,77.0,NaN,NaN,False
77,NIFTY,UP,76,30.5,True,True,False,-45.5,-20.8,15.0,46,60.9,1.28,5.74,41.3,-0.63,True,24059.60,23990.87,0.29,-0.11,0.40,False,Index,76.8,NaN,NaN,False
30,JSWSTEEL,UP,28,43.5,False,False,False,15.5,46.2,79.3,39,61.5,3.30,8.49,25.6,-4.36,True,1318.60,1265.27,4.04,1.43,0.60,False,Stock,75.9,NaN,NaN,False
121,RADICO,UP,174,52.0,True,True,True,-122.0,-91.0,-35.9,29,72.4,7.59,10.66,37.9,-4.68,True,4448.30,4401.08,1.06,53.71,4.76,True,Stock,74.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.16pp),⚠ HIGH GAP RISK (>10.0%),False
84,BAJAJFINSV,UP,77,51.0,True,False,False,-26.0,12.0,36.3,34,58.8,3.96,6.00,38.2,-1.28,True,1976.10,1953.53,1.14,10.56,2.12,False,Stock,74.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.53pp),NaN,False
38,AUBANK,UP,29,55.0,False,False,False,26.0,58.5,87.9,24,70.8,4.54,6.31,58.3,1.06,True,1082.90,1053.42,2.72,2.16,1.21,False,Stock,74.2,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.94pp),NaN,False
49,ASTRAL,UP,39,50.0,False,False,False,11.0,46.0,87.2,32,65.6,3.46,7.25,50.0,0.43,True,1510.50,1448.71,4.09,2.89,3.87,False,Stock,73.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.26pp),NaN,False
99,COFORGE,UP,116,55.5,True,True,False,-60.5,-28.0,33.3,30,70.0,8.66,8.08,50.0,0.18,True,1989.80,1843.16,7.37,45.44,6.44,True,Stock,73.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.09pp),⚠ HIGH GAP RISK (>10.0%),False
100,TORNTPHARM,UP,116,57.5,True,True,False,-58.5,-14.0,22.3,29,58.6,2.54,6.93,27.6,-3.19,True,4956.50,4705.97,5.05,13.14,0.41,False,Stock,73.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.85pp),NaN,False
8,NMDC,UP,6,43.0,False,False,False,37.0,72.2,113.8,36,66.7,3.70,10.08,38.9,-4.27,True,85.96,81.41,5.30,-2.55,2.64,False,Stock,71.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.03pp),NaN,False
17,BEL,UP,19,38.0,False,False,False,19.0,43.0,83.0,41,53.7,3.72,7.67,34.1,-4.01,True,412.15,394.10,4.38,0.40,1.18,False,Stock,70.0,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.72pp),NaN,False
69,PNBHOUSING,UP,61,45.0,True,False,False,-16.0,25.0,73.5,28,57.1,7.52,7.92,53.6,2.35,True,1147.80,1100.88,4.09,8.73,0.36,False,Stock,69.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.12pp),NaN,False
101,CIPLA,UP,131,38.5,True,True,False,-92.5,-32.8,29.0,32,62.5,0.94,7.22,43.8,-1.18,True,1411.00,1391.45,1.39,8.05,5.63,True,Stock,69.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.34pp),NaN,False

In [12]:
top25_up_by_age = top25_up.sort_values("trend_age_days", ascending=True)
print("SORTED BY: trend_age_days ascending — same 25 shares as top25_up, just re-ordered by age")
top25_up_by_age

SORTED BY: trend_age_days ascending — same 25 shares as top25_up, just re-ordered by age

,symbol,direction,trend_age_days,median_duration,past_median,past_75th_pct,past_90th_pct,runway_left_vs_median,runway_left_vs_p75,runway_left_vs_p90,dir_flips,dir_win_rate,dir_median_move,worst_day,opp_win_rate,opp_median_move,signal_works_here,spot,flip_level,buffer_to_flip_pct,moved_since_entry_pct,entry_day_move,born_on_outlier_day,security_type,trend_score,outlier_reliance_flag,gap_risk_flag,thin_sample
2,AXISBANK,UP,1,54.0,False,False,False,53.0,87.0,112.7,34,67.6,3.66,7.57,38.2,-1.36,True,1257.50,1209.49,3.82,-3.27,2.77,False,Stock,87.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.40pp),NaN,False
8,NMDC,UP,6,43.0,False,False,False,37.0,72.2,113.8,36,66.7,3.70,10.08,38.9,-4.27,True,85.45,81.41,4.73,-3.13,2.64,False,Stock,71.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.03pp),NaN,False
17,BEL,UP,19,38.0,False,False,False,19.0,43.0,83.0,41,53.7,3.72,7.67,34.1,-4.01,True,410.50,394.10,4.00,0.00,1.18,False,Stock,69.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.72pp),NaN,False
27,TATASTEEL,UP,27,43.5,False,False,False,16.5,44.2,80.0,38,65.8,3.76,8.57,42.1,-1.62,True,183.16,180.25,1.59,-5.09,1.07,False,Stock,79.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.92pp),NaN,False
30,HINDALCO,UP,28,43.0,False,False,False,15.0,46.2,87.9,37,64.9,4.37,10.98,35.1,-2.35,True,1014.40,997.57,1.66,-0.55,2.52,False,Stock,79.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 5.15pp),NaN,False
29,JSWSTEEL,UP,28,43.5,False,False,False,15.5,46.2,79.3,39,61.5,3.30,8.49,25.6,-4.36,True,1314.00,1265.27,3.71,1.08,0.60,False,Stock,75.8,NaN,NaN,False
32,LT,UP,29,36.0,False,False,False,7.0,38.8,78.0,40,65.0,2.70,5.91,52.5,0.04,True,3999.00,3940.99,1.45,-0.65,2.19,False,Stock,83.4,NaN,NaN,False
35,FINNIFTY,UP,29,33.5,False,False,False,4.5,30.2,73.3,46,63.0,2.36,3.37,43.5,-1.33,True,26003.90,25963.27,0.16,-3.63,1.47,False,Index,82.8,NaN,NaN,False
36,AUBANK,UP,29,55.0,False,False,False,26.0,58.5,87.9,24,70.8,4.54,6.31,58.3,1.06,True,1080.00,1053.42,2.46,1.89,1.21,False,Stock,74.1,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.94pp),NaN,False
41,JINDALSTEL,UP,32,42.0,False,False,False,10.0,45.0,69.5,38,71.1,6.52,10.29,36.8,-2.78,True,1148.00,1106.25,3.64,4.14,0.80,False,Stock,78.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.48pp),NaN,False
47,ASTRAL,UP,39,50.0,False,False,False,11.0,46.0,87.2,32,65.6,3.46,7.25,50.0,0.43,True,1506.70,1448.71,3.85,2.63,3.87,False,Stock,73.5,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.26pp),NaN,False
66,NESTLEIND,UP,57,47.5,True,False,False,-9.5,33.8,70.5,33,57.6,2.99,5.44,39.4,-1.62,True,1436.50,1427.21,0.65,-2.52,0.95,False,Stock,79.4,NaN,NaN,False
67,PNBHOUSING,UP,61,45.0,True,False,False,-16.0,25.0,73.5,28,57.1,7.52,7.92,53.6,2.35,True,1143.10,1100.88,3.69,8.29,0.36,False,Stock,69.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.12pp),NaN,False
72,MIDCPNIFTY,UP,75,15.0,True,True,True,-60.0,-48.0,-26.0,91,65.9,2.11,4.91,42.9,-0.45,True,14813.35,14650.35,1.10,1.49,0.14,False,Index,84.5,NaN,NaN,False
73,NIFTY,UP,76,30.5,True,True,False,-45.5,-20.8,15.0,46,60.9,1.28,5.74,41.3,-0.63,True,24055.80,23990.87,0.27,-0.12,0.40,False,Index,76.8,NaN,NaN,False
80,BAJAJFINSV,UP,77,51.0,True,False,False,-26.0,12.0,36.3,34,58.8,3.96,6.00,38.2,-1.28,True,1968.00,1953.53,0.74,10.11,2.12,False,Stock,73.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 8.53pp),NaN,False
79,SENSEX,UP,77,30.0,True,True,False,-47.0,-23.0,13.6,49,59.2,1.32,5.94,40.8,-0.59,True,76944.28,76654.85,0.38,0.18,0.71,False,Index,76.9,NaN,NaN,False
78,TITAN,UP,77,41.0,True,False,False,-36.0,0.8,37.4,35,62.9,4.65,6.73,37.1,-2.58,True,5030.50,4928.12,2.04,15.96,1.27,False,Stock,83.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 4.74pp),NaN,False
92,DIXON,UP,102,38.0,True,True,False,-64.0,-19.0,25.0,27,70.4,6.10,8.95,48.1,-1.11,True,14500.00,13688.92,5.59,23.70,4.12,True,Stock,67.7,⚠ RELIES ON OUTLIER WINS (avg-median gap 11.57pp),NaN,False
94,COFORGE,UP,116,55.5,True,True,False,-60.5,-28.0,33.3,30,70.0,8.66,8.08,50.0,0.18,True,1984.10,1843.16,7.10,45.03,6.44,True,Stock,73.4,⚠ RELIES ON OUTLIER WINS (avg-median gap 6.09pp),⚠ HIGH GAP RISK (>10.0%),False
93,TORNTPHARM,UP,116,57.5,True,True,False,-58.5,-14.0,22.3,29,58.6,2.54,6.93,27.6,-3.19,True,4976.50,4705.97,5.44,13.60,0.41,False,Stock,72.6,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.85pp),NaN,False
95,CIPLA,UP,131,38.5,True,True,False,-92.5,-32.8,29.0,32,62.5,0.94,7.22,43.8,-1.18,True,1417.00,1391.45,1.80,8.51,5.63,True,Stock,68.8,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.34pp),NaN,False
110,BAJAJHLDNG,UP,146,59.5,True,True,True,-86.5,-55.0,-10.7,30,70.0,4.10,7.45,46.7,-0.92,True,11365.00,10807.72,4.90,13.99,7.94,True,Stock,86.9,⚠ RELIES ON OUTLIER WINS (avg-median gap 3.85pp),NaN,False
114,BOSCHLTD,UP,152,45.5,True,True,True,-106.5,-65.0,-20.6,31,64.5,3.40,5.89,64.5,1.91,True,48225.00,46082.99,4.44,50.07,4.90,True,Stock,81.5,NaN,NaN,False
115,RADICO,UP,174,52.0,True,True,True,-122.0,-91.0,-35.9,29,72.4,7.59,10.66,37.9,-4.68,True,4430.00,4401.08,0.65,53.08,4.76,True,Stock,74.3,⚠ RELIES ON OUTLIER WINS (avg-median gap 7.16pp),⚠ HIGH GAP RISK (>10.0%),False